export interface Database {
  public: {
    Tables: {
      surveys: {
        Row: {
          id: string;
          survey_title: string;
          surveyor_name: string;
          client_name: string;
          project_number: string;
          origin_address: string;
          destination_address: string;
          description: string;
          notes: string;
          enable_vehicle_trace: boolean;
          enable_alert_log: boolean;
          active: boolean;
          created_at: string;
          cloud_upload_status: string | null;
          sync_id: string | null;
          export_target: string | null;
          convoy_id: string | null;
          fleet_unit_role: string | null;
          planned_route_id: string | null;
          route_analysis: string | null;
          ai_user_model_id: string | null;
          ai_history_score: number | null;
          intervention_type: string | null;
          checklist_completed: boolean;
        };
        Insert: {
          id?: string;
          survey_title: string;
          surveyor_name: string;
          client_name: string;
          project_number: string;
          origin_address: string;
          destination_address: string;
          description: string;
          notes: string;
          enable_vehicle_trace: boolean;
          enable_alert_log: boolean;
          active?: boolean;
          created_at?: string;
          cloud_upload_status?: string | null;
          sync_id?: string | null;
          export_target?: string | null;
          convoy_id?: string | null;
          fleet_unit_role?: string | null;
          planned_route_id?: string | null;
          route_analysis?: string | null;
          ai_user_model_id?: string | null;
          ai_history_score?: number | null;
          intervention_type?: string | null;
          checklist_completed?: boolean;
        };
        Update: {
          id?: string;
          survey_title?: string;
          surveyor_name?: string;
          client_name?: string;
          project_number?: string;
          origin_address?: string;
          destination_address?: string;
          description?: string;
          notes?: string;
          enable_vehicle_trace?: boolean;
          enable_alert_log?: boolean;
          active?: boolean;
          created_at?: string;
          cloud_upload_status?: string | null;
          sync_id?: string | null;
          export_target?: string | null;
          convoy_id?: string | null;
          fleet_unit_role?: string | null;
          planned_route_id?: string | null;
          route_analysis?: string | null;
          ai_user_model_id?: string | null;
          ai_history_score?: number | null;
          intervention_type?: string | null;
          checklist_completed?: boolean;
        };
      };
      measurements: {
        Row: {
          id: string;
          rel: number;
          alt_gps: number;
          latitude: number;
          longitude: number;
          mile_marker: number;
          poi_type: string;
          notes: string | null;
          image_url: string | null;
          add_method: 'manual' | 'log_all' | 'object_detected' | 'from_slave';
          generated_by_ai: boolean;
          from_high_pole: boolean;
          from_slave: boolean;
          cloud_upload_status: string | null;
          photo_cloud_link: string | null;
          collectable: boolean;
          slave_device_id: string | null;
          replay_key: string | null;
          frame_index: number | null;
          utc_date: string;
          utc_time: string;
          speed: number;
          heading: number;
          created_at: string;
          user_id: string;
          road_number: number | null;
          poi_number: number | null;
        };
        Insert: {
          id?: string;
          rel: number;
          alt_gps: number;
          latitude: number;
          longitude: number;
          mile_marker?: number;
          poi_type?: string;
          notes?: string | null;
          image_url?: string | null;
          add_method?: 'manual' | 'log_all' | 'object_detected' | 'from_slave';
          generated_by_ai?: boolean;
          from_high_pole?: boolean;
          from_slave?: boolean;
          cloud_upload_status?: string | null;
          photo_cloud_link?: string | null;
          collectable?: boolean;
          slave_device_id?: string | null;
          replay_key?: string | null;
          frame_index?: number | null;
          utc_date: string;
          utc_time: string;
          speed: number;
          heading: number;
          created_at?: string;
          user_id: string;
          road_number?: number | null;
          poi_number?: number | null;
        };
        Update: {
          id?: string;
          rel?: number;
          alt_gps?: number;
          latitude?: number;
          longitude?: number;
          mile_marker?: number;
          poi_type?: string;
          notes?: string | null;
          image_url?: string | null;
          add_method?: 'manual' | 'log_all' | 'object_detected' | 'from_slave';
          generated_by_ai?: boolean;
          from_high_pole?: boolean;
          from_slave?: boolean;
          cloud_upload_status?: string | null;
          photo_cloud_link?: string | null;
          collectable?: boolean;
          slave_device_id?: string | null;
          replay_key?: string | null;
          frame_index?: number | null;
          utc_date?: string;
          utc_time?: string;
          speed?: number;
          heading?: number;
          created_at?: string;
          user_id?: string;
          road_number?: number | null;
          poi_number?: number | null;
        };
      };
    };
  };
}