import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import type { VehicleProfile, EnvelopeSettings, ClearanceViolation } from '@/../../shared/schema';

// Default vehicle profiles - Comprehensive OS/OW Equipment Configurations
const DEFAULT_PROFILES: VehicleProfile[] = [
  // STANDARD TRAILERS
  {
    id: 'standard-flatbed-5axle',
    name: 'Standard Flatbed (5-Axle)',
    width: 2.6, // 8.5 ft
    height: 4.15, // Total envelope: deck 1.5m + typical cargo 2.65m = 4.15m (13.6 ft)
    length: 16.2, // 53 ft max
    widthUnit: 'meters',
    heightUnit: 'meters',
    lengthUnit: 'meters',
    weightCapacity: 24000, // 53,000 lbs
    weightUnit: 'kg',
    axleConfiguration: '5 axles standard flatbed',
    description: 'Tractor + 2-axle flatbed, 48-53 ft length (deck height: 1.5m)',
    articulationConfig: {
      hasJeep: false,
      hasSteerable: false,
      jointType: 'fifth_wheel',
      maxArticulation: 45,
      tractorAxles: 2,
      trailerAxles: 3, // 5 - 2 = 3
    },
    overallDimensions: {
      overallLength: 24.2, // 8.0m tractor + 16.2m trailer
      overallHeight: 4.15,
      transportWidth: 2.6,
      curbWeight: 24000,
    },
    segments: [
      {
        id: 'tractor',
        type: 'tractor',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetRear: 7.5,
        wheelbase: 4.5,
        fifthWheelOffset: 0.5,
        driveGroupSpread: 1.4,
      },
      {
        id: 'trailer',
        type: 'trailer',
        referenceLength: 16.2,
        usableDeckLength: 16.2,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        kingpinSetback: 1.0,
        bogieSlideRange: 0.6,
      },
    ],
    axleGroups: [
      {
        segmentId: 'tractor',
        groupId: 'tractor-steer',
        positionFromSegmentFront: 0.5,
        axleCount: 1,
        spread: 0,
        steerable: true,
        loadShare: 0.15,
      },
      {
        segmentId: 'tractor',
        groupId: 'tractor-drive',
        positionFromSegmentFront: 5.5,
        axleCount: 2,
        spread: 1.4,
        steerable: false,
        loadShare: 0.35,
      },
      {
        segmentId: 'trailer',
        groupId: 'trailer-bogie',
        positionFromSegmentFront: 14.5,
        axleCount: 3,
        spread: 2.6,
        steerable: false,
        loadShare: 0.50,
      },
    ],
    articulationJoints: [
      {
        id: 'tractor-trailer-fifth-wheel',
        type: 'fifth_wheel',
        fromSegmentId: 'tractor',
        toSegmentId: 'trailer',
        positionOnFrom: 7.5,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 45,
        lateralOffset: 0,
      },
    ],
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'step-deck-5axle',
    name: 'Step Deck (5-Axle)',
    width: 2.6, // 8.5 ft
    height: 4.0, // Total envelope: lower deck 1.0m + cargo 3.0m = 4.0m (13.1 ft)
    length: 16.2, // 53 ft max
    widthUnit: 'meters',
    heightUnit: 'meters',
    lengthUnit: 'meters',
    weightCapacity: 23600, // 52,000 lbs
    weightUnit: 'kg',
    axleConfiguration: '5 axles step deck',
    description: 'Tractor + 2-axle step deck (upper deck: 1.5m, lower deck: 1.0m)',
    articulationConfig: {
      hasJeep: false,
      hasSteerable: false,
      jointType: 'fifth_wheel',
      maxArticulation: 45,
      tractorAxles: 2,
      trailerAxles: 3, // 5 - 2 = 3
    },
    overallDimensions: {
      overallLength: 24.2, // 8.0m tractor + 16.2m trailer
      overallHeight: 4.0,
      transportWidth: 2.6,
      curbWeight: 23600,
    },
    segments: [
      {
        id: 'tractor',
        type: 'tractor',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetRear: 7.5,
        wheelbase: 4.5,
        fifthWheelOffset: 0.5,
        driveGroupSpread: 1.4,
      },
      {
        id: 'trailer',
        type: 'trailer',
        referenceLength: 16.2,
        usableDeckLength: 16.2,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        kingpinSetback: 1.0,
        bogieSlideRange: 0.6,
      },
    ],
    axleGroups: [
      {
        segmentId: 'tractor',
        groupId: 'tractor-steer',
        positionFromSegmentFront: 0.5,
        axleCount: 1,
        spread: 0,
        steerable: true,
        loadShare: 0.15,
      },
      {
        segmentId: 'tractor',
        groupId: 'tractor-drive',
        positionFromSegmentFront: 5.5,
        axleCount: 2,
        spread: 1.4,
        steerable: false,
        loadShare: 0.35,
      },
      {
        segmentId: 'trailer',
        groupId: 'trailer-bogie',
        positionFromSegmentFront: 14.5,
        axleCount: 3,
        spread: 2.6,
        steerable: false,
        loadShare: 0.50,
      },
    ],
    articulationJoints: [
      {
        id: 'tractor-trailer-fifth-wheel',
        type: 'fifth_wheel',
        fromSegmentId: 'tractor',
        toSegmentId: 'trailer',
        positionOnFrom: 7.5,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 45,
        lateralOffset: 0,
      },
    ],
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
  // LOWBOY/RGN TRAILERS
  {
    id: '2axle-lowboy',
    name: '2-Axle Lowboy',
    width: 2.6, // 8.5 ft
    height: 4.0, // Total envelope: deck 0.61m + cargo 3.4m = 4.0m (13.1 ft)
    length: 8.8, // 29 ft well max
    widthUnit: 'meters',
    heightUnit: 'meters',
    lengthUnit: 'meters',
    weightCapacity: 21800, // 48,000 lbs
    weightUnit: 'kg',
    axleConfiguration: '2 axles fixed neck lowboy',
    description: 'Fixed neck lowboy, 24-29 ft well (deck height: 0.61m)',
    articulationConfig: {
      hasJeep: false,
      hasSteerable: false,
      jointType: 'fifth_wheel',
      maxArticulation: 45,
      tractorAxles: 2,
      trailerAxles: 2, // 2 - 2 = 0, min 2
    },
    overallDimensions: {
      overallLength: 16.8, // 8.0m tractor + 8.8m trailer
      overallHeight: 4.0,
      transportWidth: 2.6,
      curbWeight: 21800,
    },
    segments: [
      {
        id: 'tractor',
        type: 'tractor',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetRear: 7.5,
        wheelbase: 4.5,
        fifthWheelOffset: 0.5,
        driveGroupSpread: 1.4,
      },
      {
        id: 'trailer',
        type: 'trailer',
        referenceLength: 8.8,
        usableDeckLength: 8.8,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        kingpinSetback: 0.8,
        bogieSlideRange: 0.4,
      },
    ],
    axleGroups: [
      {
        segmentId: 'tractor',
        groupId: 'tractor-steer',
        positionFromSegmentFront: 0.5,
        axleCount: 1,
        spread: 0,
        steerable: true,
        loadShare: 0.18,
      },
      {
        segmentId: 'tractor',
        groupId: 'tractor-drive',
        positionFromSegmentFront: 5.5,
        axleCount: 2,
        spread: 1.4,
        steerable: false,
        loadShare: 0.40,
      },
      {
        segmentId: 'trailer',
        groupId: 'trailer-bogie',
        positionFromSegmentFront: 7.0,
        axleCount: 2,
        spread: 1.3,
        steerable: false,
        loadShare: 0.42,
      },
    ],
    articulationJoints: [
      {
        id: 'tractor-trailer-fifth-wheel',
        type: 'fifth_wheel',
        fromSegmentId: 'tractor',
        toSegmentId: 'trailer',
        positionOnFrom: 7.5,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 45,
        lateralOffset: 0,
      },
    ],
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '3axle-rgn',
    name: '3-Axle RGN',
    width: 2.6, // 8.5 ft
    height: 4.0, // Total envelope: deck 0.61m + cargo 3.4m = 4.0m (13.1 ft)
    length: 8.8, // 29 ft well
    widthUnit: 'meters',
    heightUnit: 'meters',
    lengthUnit: 'meters',
    weightCapacity: 25000, // 55,000 lbs
    weightUnit: 'kg',
    axleConfiguration: '3 axles hydraulic RGN',
    description: 'Hydraulic detachable gooseneck, 29 ft well (deck height: 0.61m)',
    articulationConfig: {
      hasJeep: false,
      hasSteerable: false,
      jointType: 'fifth_wheel',
      maxArticulation: 45,
      tractorAxles: 2,
      trailerAxles: 2, // 3 - 2 = 1, min 2
    },
    overallDimensions: {
      overallLength: 16.8,
      overallHeight: 4.0,
      transportWidth: 2.6,
      curbWeight: 25000,
    },
    segments: [
      {
        id: 'tractor',
        type: 'tractor',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetRear: 7.5,
        wheelbase: 4.5,
        fifthWheelOffset: 0.5,
        driveGroupSpread: 1.4,
      },
      {
        id: 'trailer',
        type: 'trailer',
        referenceLength: 8.8,
        usableDeckLength: 8.8,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        kingpinSetback: 0.8,
        bogieSlideRange: 0.4,
      },
    ],
    axleGroups: [
      {
        segmentId: 'tractor',
        groupId: 'tractor-steer',
        positionFromSegmentFront: 0.5,
        axleCount: 1,
        spread: 0,
        steerable: true,
        loadShare: 0.18,
      },
      {
        segmentId: 'tractor',
        groupId: 'tractor-drive',
        positionFromSegmentFront: 5.5,
        axleCount: 2,
        spread: 1.4,
        steerable: false,
        loadShare: 0.38,
      },
      {
        segmentId: 'trailer',
        groupId: 'trailer-bogie',
        positionFromSegmentFront: 7.0,
        axleCount: 2,
        spread: 1.3,
        steerable: false,
        loadShare: 0.44,
      },
    ],
    articulationJoints: [
      {
        id: 'tractor-trailer-fifth-wheel',
        type: 'fifth_wheel',
        fromSegmentId: 'tractor',
        toSegmentId: 'trailer',
        positionOnFrom: 7.5,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 45,
        lateralOffset: 0,
      },
    ],
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '4axle-rgn',
    name: '4-Axle RGN',
    width: 2.6, // 8.5 ft
    height: 4.0, // Total envelope: deck 0.61m + cargo 3.4m = 4.0m (13.1 ft)
    length: 10.7, // 35 ft well max
    widthUnit: 'meters',
    heightUnit: 'meters',
    lengthUnit: 'meters',
    weightCapacity: 36300, // 80,000 lbs
    weightUnit: 'kg',
    axleConfiguration: '4 axles RGN',
    description: 'Removable gooseneck, 29-35 ft well (deck height: 0.61m)',
    articulationConfig: {
      hasJeep: false,
      hasSteerable: false,
      jointType: 'fifth_wheel',
      maxArticulation: 45,
      tractorAxles: 2,
      trailerAxles: 2, // 4 - 2 = 2
    },
    overallDimensions: {
      overallLength: 18.7,
      overallHeight: 4.0,
      transportWidth: 2.6,
      curbWeight: 36300,
    },
    segments: [
      {
        id: 'tractor',
        type: 'tractor',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetRear: 7.5,
        wheelbase: 4.5,
        fifthWheelOffset: 0.5,
        driveGroupSpread: 1.4,
      },
      {
        id: 'trailer',
        type: 'trailer',
        referenceLength: 10.7,
        usableDeckLength: 10.7,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        kingpinSetback: 1.0,
        bogieSlideRange: 0.5,
      },
    ],
    axleGroups: [
      {
        segmentId: 'tractor',
        groupId: 'tractor-steer',
        positionFromSegmentFront: 0.5,
        axleCount: 1,
        spread: 0,
        steerable: true,
        loadShare: 0.15,
      },
      {
        segmentId: 'tractor',
        groupId: 'tractor-drive',
        positionFromSegmentFront: 5.5,
        axleCount: 2,
        spread: 1.4,
        steerable: false,
        loadShare: 0.35,
      },
      {
        segmentId: 'trailer',
        groupId: 'trailer-bogie',
        positionFromSegmentFront: 8.9,
        axleCount: 2,
        spread: 1.3,
        steerable: false,
        loadShare: 0.50,
      },
    ],
    articulationJoints: [
      {
        id: 'tractor-trailer-fifth-wheel',
        type: 'fifth_wheel',
        fromSegmentId: 'tractor',
        toSegmentId: 'trailer',
        positionOnFrom: 7.5,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 45,
        lateralOffset: 0,
      },
    ],
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '6axle-rgn',
    name: '6-Axle RGN',
    width: 2.6, // 8.5 ft
    height: 4.0, // Total envelope: deck 0.61m + cargo 3.4m = 4.0m (13.1 ft)
    length: 10.7, // 35 ft well max
    widthUnit: 'meters',
    heightUnit: 'meters',
    lengthUnit: 'meters',
    weightCapacity: 36300, // 80,000 lbs
    weightUnit: 'kg',
    axleConfiguration: '6 axles RGN',
    description: 'Removable gooseneck, 29-35 ft well (deck height: 0.61m)',
    articulationConfig: {
      hasJeep: true,
      jeepAxles: 2,
      jeepLength: 3.5,
      hasSteerable: false,
      jointType: 'fifth_wheel',
      maxArticulation: 45,
      tractorAxles: 2,
      trailerAxles: 2, // 6 - 2 - 2 = 2
    },
    overallDimensions: {
      overallLength: 22.2, // 8.0 tractor + 3.5 jeep + 10.7 trailer
      overallHeight: 4.0,
      transportWidth: 2.6,
      curbWeight: 36300,
    },
    segments: [
      {
        id: 'tractor',
        type: 'tractor',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetRear: 7.5,
        wheelbase: 4.5,
        fifthWheelOffset: 0.5,
        driveGroupSpread: 1.4,
      },
      {
        id: 'jeep',
        type: 'jeep_dolly',
        referenceLength: 3.5,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.3,
        couplerOffsetRear: 3.2,
        drawbarLength: 2.5,
      },
      {
        id: 'trailer',
        type: 'trailer',
        referenceLength: 10.7,
        usableDeckLength: 10.7,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        kingpinSetback: 1.0,
        bogieSlideRange: 0.5,
      },
    ],
    axleGroups: [
      {
        segmentId: 'tractor',
        groupId: 'tractor-steer',
        positionFromSegmentFront: 0.5,
        axleCount: 1,
        spread: 0,
        steerable: true,
        loadShare: 0.12,
      },
      {
        segmentId: 'tractor',
        groupId: 'tractor-drive',
        positionFromSegmentFront: 5.5,
        axleCount: 2,
        spread: 1.4,
        steerable: false,
        loadShare: 0.28,
      },
      {
        segmentId: 'jeep',
        groupId: 'jeep-axles',
        positionFromSegmentFront: 1.8,
        axleCount: 2,
        spread: 1.3,
        steerable: false,
        loadShare: 0.20,
      },
      {
        segmentId: 'trailer',
        groupId: 'trailer-bogie',
        positionFromSegmentFront: 8.9,
        axleCount: 2,
        spread: 1.3,
        steerable: false,
        loadShare: 0.40,
      },
    ],
    articulationJoints: [
      {
        id: 'tractor-jeep-pivot',
        type: 'pivot',
        fromSegmentId: 'tractor',
        toSegmentId: 'jeep',
        positionOnFrom: 7.5,
        positionOnTo: 0.3,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'jeep-trailer-kingpin',
        type: 'king_pin',
        fromSegmentId: 'jeep',
        toSegmentId: 'trailer',
        positionOnFrom: 3.2,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
    ],
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '7axle-rgn',
    name: '7-Axle RGN',
    width: 2.6, // 8.5 ft
    height: 4.0, // Total envelope: deck 0.61m + cargo 3.4m = 4.0m (13.1 ft)
    length: 15.2, // 50 ft well max
    widthUnit: 'meters',
    heightUnit: 'meters',
    lengthUnit: 'meters',
    weightCapacity: 38600, // 85,000 lbs
    weightUnit: 'kg',
    axleConfiguration: '7 axles RGN',
    description: 'Removable gooseneck, 26-50 ft well (deck height: 0.61m)',
    articulationConfig: {
      hasJeep: true,
      jeepAxles: 2,
      jeepLength: 3.5,
      hasSteerable: false,
      jointType: 'fifth_wheel',
      maxArticulation: 45,
      tractorAxles: 2,
      trailerAxles: 3, // 7 - 2 - 2 = 3
    },
    overallDimensions: {
      overallLength: 26.7, // 8.0 + 3.5 + 15.2
      overallHeight: 4.0,
      transportWidth: 2.6,
      curbWeight: 38600,
    },
    segments: [
      {
        id: 'tractor',
        type: 'tractor',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetRear: 7.5,
        wheelbase: 4.5,
        fifthWheelOffset: 0.5,
        driveGroupSpread: 1.4,
      },
      {
        id: 'jeep',
        type: 'jeep_dolly',
        referenceLength: 3.5,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.3,
        couplerOffsetRear: 3.2,
        drawbarLength: 2.5,
      },
      {
        id: 'trailer',
        type: 'trailer',
        referenceLength: 15.2,
        usableDeckLength: 15.2,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        kingpinSetback: 1.2,
        bogieSlideRange: 0.8,
      },
    ],
    axleGroups: [
      {
        segmentId: 'tractor',
        groupId: 'tractor-steer',
        positionFromSegmentFront: 0.5,
        axleCount: 1,
        spread: 0,
        steerable: true,
        loadShare: 0.12,
      },
      {
        segmentId: 'tractor',
        groupId: 'tractor-drive',
        positionFromSegmentFront: 5.5,
        axleCount: 2,
        spread: 1.4,
        steerable: false,
        loadShare: 0.26,
      },
      {
        segmentId: 'jeep',
        groupId: 'jeep-axles',
        positionFromSegmentFront: 1.8,
        axleCount: 2,
        spread: 1.3,
        steerable: false,
        loadShare: 0.18,
      },
      {
        segmentId: 'trailer',
        groupId: 'trailer-bogie',
        positionFromSegmentFront: 12.5,
        axleCount: 3,
        spread: 2.6,
        steerable: false,
        loadShare: 0.44,
      },
    ],
    articulationJoints: [
      {
        id: 'tractor-jeep-pivot',
        type: 'pivot',
        fromSegmentId: 'tractor',
        toSegmentId: 'jeep',
        positionOnFrom: 7.5,
        positionOnTo: 0.3,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'jeep-trailer-kingpin',
        type: 'king_pin',
        fromSegmentId: 'jeep',
        toSegmentId: 'trailer',
        positionOnFrom: 3.2,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
    ],
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '8axle-rgn-extendable',
    name: '8-Axle RGN Extendable',
    width: 2.6, // 8.5 ft
    height: 4.1, // Total envelope: deck 0.76m + cargo 3.34m = 4.1m (13.5 ft)
    length: 20.1, // 66 ft well max
    widthUnit: 'meters',
    heightUnit: 'meters',
    lengthUnit: 'meters',
    weightCapacity: 46300, // 102,000 lbs
    weightUnit: 'kg',
    axleConfiguration: '8 axles RGN extendable',
    description: 'Removable gooseneck extendable, 50-66 ft well (deck height: 0.76m)',
    articulationConfig: {
      hasJeep: true,
      jeepAxles: 2,
      jeepLength: 4.0,
      hasSteerable: false,
      jointType: 'fifth_wheel',
      maxArticulation: 45,
      tractorAxles: 2,
      trailerAxles: 4, // 8 - 2 - 2 = 4
    },
    overallDimensions: {
      overallLength: 32.1, // 8.0 + 4.0 + 20.1
      overallHeight: 4.1,
      transportWidth: 2.6,
      curbWeight: 46300,
    },
    segments: [
      {
        id: 'tractor',
        type: 'tractor',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetRear: 7.5,
        wheelbase: 4.5,
        fifthWheelOffset: 0.5,
        driveGroupSpread: 1.4,
      },
      {
        id: 'jeep',
        type: 'jeep_dolly',
        referenceLength: 4.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.3,
        couplerOffsetRear: 3.7,
        drawbarLength: 3.0,
      },
      {
        id: 'trailer',
        type: 'trailer',
        referenceLength: 20.1,
        usableDeckLength: 20.1,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        kingpinSetback: 1.5,
        bogieSlideRange: 1.0,
      },
    ],
    axleGroups: [
      {
        segmentId: 'tractor',
        groupId: 'tractor-steer',
        positionFromSegmentFront: 0.5,
        axleCount: 1,
        spread: 0,
        steerable: true,
        loadShare: 0.10,
      },
      {
        segmentId: 'tractor',
        groupId: 'tractor-drive',
        positionFromSegmentFront: 5.5,
        axleCount: 2,
        spread: 1.4,
        steerable: false,
        loadShare: 0.22,
      },
      {
        segmentId: 'jeep',
        groupId: 'jeep-axles',
        positionFromSegmentFront: 2.0,
        axleCount: 2,
        spread: 1.3,
        steerable: false,
        loadShare: 0.18,
      },
      {
        segmentId: 'trailer',
        groupId: 'trailer-bogie',
        positionFromSegmentFront: 16.0,
        axleCount: 4,
        spread: 3.9,
        steerable: false,
        loadShare: 0.50,
      },
    ],
    articulationJoints: [
      {
        id: 'tractor-jeep-pivot',
        type: 'pivot',
        fromSegmentId: 'tractor',
        toSegmentId: 'jeep',
        positionOnFrom: 7.5,
        positionOnTo: 0.3,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'jeep-trailer-kingpin',
        type: 'king_pin',
        fromSegmentId: 'jeep',
        toSegmentId: 'trailer',
        positionOnFrom: 3.7,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
    ],
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '9axle-lowboy',
    name: '9-Axle Lowboy',
    width: 2.6, // 8.5 ft
    height: 4.1, // Total envelope: deck 0.76m + cargo 3.34m = 4.1m (13.5 ft)
    length: 20.1, // 66 ft lower deck max
    widthUnit: 'meters',
    heightUnit: 'meters',
    lengthUnit: 'meters',
    weightCapacity: 56700, // 125,000 lbs
    weightUnit: 'kg',
    axleConfiguration: '9 axles low profile stepdeck extendable',
    description: 'Low profile double drop, 25-66 ft lower deck (deck height: 0.76m)',
    articulationConfig: {
      hasJeep: true,
      jeepAxles: 3,
      jeepLength: 4.5,
      hasSteerable: false,
      jointType: 'pivot',
      maxArticulation: 60,
      tractorAxles: 2,
      trailerAxles: 4, // 9 - 2 - 3 = 4
    },
    overallDimensions: {
      overallLength: 32.6, // 8.0 + 4.5 + 20.1
      overallHeight: 4.1,
      transportWidth: 2.6,
      curbWeight: 56700,
    },
    segments: [
      {
        id: 'tractor',
        type: 'tractor',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetRear: 7.5,
        wheelbase: 4.5,
        fifthWheelOffset: 0.5,
        driveGroupSpread: 1.4,
      },
      {
        id: 'jeep',
        type: 'jeep_dolly',
        referenceLength: 4.5,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.3,
        couplerOffsetRear: 4.2,
        drawbarLength: 3.2,
      },
      {
        id: 'trailer',
        type: 'trailer',
        referenceLength: 20.1,
        usableDeckLength: 20.1,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        kingpinSetback: 1.5,
        bogieSlideRange: 1.0,
      },
    ],
    axleGroups: [
      {
        segmentId: 'tractor',
        groupId: 'tractor-steer',
        positionFromSegmentFront: 0.5,
        axleCount: 1,
        spread: 0,
        steerable: true,
        loadShare: 0.10,
      },
      {
        segmentId: 'tractor',
        groupId: 'tractor-drive',
        positionFromSegmentFront: 5.5,
        axleCount: 2,
        spread: 1.4,
        steerable: false,
        loadShare: 0.20,
      },
      {
        segmentId: 'jeep',
        groupId: 'jeep-axles',
        positionFromSegmentFront: 2.2,
        axleCount: 3,
        spread: 2.6,
        steerable: false,
        loadShare: 0.22,
      },
      {
        segmentId: 'trailer',
        groupId: 'trailer-bogie',
        positionFromSegmentFront: 16.0,
        axleCount: 4,
        spread: 3.9,
        steerable: false,
        loadShare: 0.48,
      },
    ],
    articulationJoints: [
      {
        id: 'tractor-jeep-pivot',
        type: 'pivot',
        fromSegmentId: 'tractor',
        toSegmentId: 'jeep',
        positionOnFrom: 7.5,
        positionOnTo: 0.3,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'jeep-trailer-kingpin',
        type: 'king_pin',
        fromSegmentId: 'jeep',
        toSegmentId: 'trailer',
        positionOnFrom: 4.2,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
    ],
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '10axle-rgn',
    name: '10-Axle RGN',
    width: 2.6, // 8.5 ft
    height: 4.1, // Total envelope: deck 0.76m + cargo 3.34m = 4.1m (13.5 ft)
    length: 18.9, // 62 ft well max
    widthUnit: 'meters',
    heightUnit: 'meters',
    lengthUnit: 'meters',
    weightCapacity: 54400, // 120,000 lbs
    weightUnit: 'kg',
    axleConfiguration: '10 axles multi-axle RGN',
    description: 'Multi-axle removable gooseneck, 45-62 ft well (deck height: 0.76m)',
    articulationConfig: {
      hasJeep: true,
      jeepAxles: 3,
      jeepLength: 4.5,
      hasSteerable: true,
      steerableAxles: 4,
      steerableLength: 8,
      jointType: 'pivot',
      maxArticulation: 60,
      offTrackingReduction: 0.70,
      tractorAxles: 2,
      trailerAxles: 2, // 10 - 2 - 3 - 4 = 1, min 2
    },
    overallDimensions: {
      overallLength: 39.4, // 8.0 + 4.5 + 8.0 + 18.9
      overallHeight: 4.1,
      transportWidth: 2.6,
      curbWeight: 54400,
    },
    segments: [
      {
        id: 'tractor',
        type: 'tractor',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetRear: 7.5,
        wheelbase: 4.5,
        fifthWheelOffset: 0.5,
        driveGroupSpread: 1.4,
      },
      {
        id: 'jeep',
        type: 'jeep_dolly',
        referenceLength: 4.5,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.3,
        couplerOffsetRear: 4.2,
        drawbarLength: 3.2,
      },
      {
        id: 'steerable',
        type: 'steerable_dolly',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        couplerOffsetRear: 7.5,
        drawbarLength: 6.5,
      },
      {
        id: 'trailer',
        type: 'trailer',
        referenceLength: 18.9,
        usableDeckLength: 18.9,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        kingpinSetback: 1.5,
        bogieSlideRange: 1.0,
      },
    ],
    axleGroups: [
      {
        segmentId: 'tractor',
        groupId: 'tractor-steer',
        positionFromSegmentFront: 0.5,
        axleCount: 1,
        spread: 0,
        steerable: true,
        loadShare: 0.08,
      },
      {
        segmentId: 'tractor',
        groupId: 'tractor-drive',
        positionFromSegmentFront: 5.5,
        axleCount: 2,
        spread: 1.4,
        steerable: false,
        loadShare: 0.18,
      },
      {
        segmentId: 'jeep',
        groupId: 'jeep-axles',
        positionFromSegmentFront: 2.2,
        axleCount: 3,
        spread: 2.6,
        steerable: false,
        loadShare: 0.22,
      },
      {
        segmentId: 'steerable',
        groupId: 'steerable-axles',
        positionFromSegmentFront: 4.0,
        axleCount: 4,
        spread: 3.9,
        steerable: true,
        loadShare: 0.30,
      },
      {
        segmentId: 'trailer',
        groupId: 'trailer-bogie',
        positionFromSegmentFront: 16.0,
        axleCount: 2,
        spread: 1.3,
        steerable: false,
        loadShare: 0.22,
      },
    ],
    articulationJoints: [
      {
        id: 'tractor-jeep-pivot',
        type: 'pivot',
        fromSegmentId: 'tractor',
        toSegmentId: 'jeep',
        positionOnFrom: 7.5,
        positionOnTo: 0.3,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'jeep-steerable-kingpin',
        type: 'king_pin',
        fromSegmentId: 'jeep',
        toSegmentId: 'steerable',
        positionOnFrom: 4.2,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'steerable-trailer-kingpin',
        type: 'king_pin',
        fromSegmentId: 'steerable',
        toSegmentId: 'trailer',
        positionOnFrom: 7.5,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
    ],
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '11axle-rgn',
    name: '11-Axle RGN',
    width: 2.6, // 8.5 ft
    height: 4.1, // Total envelope: deck 0.76m + cargo 3.34m = 4.1m (13.5 ft)
    length: 18.9, // 62 ft well max
    widthUnit: 'meters',
    heightUnit: 'meters',
    lengthUnit: 'meters',
    weightCapacity: 65800, // 145,000 lbs
    weightUnit: 'kg',
    axleConfiguration: '11 axles heavy capacity RGN',
    description: 'Heavy capacity RGN, 45-62 ft well (deck height: 0.76m)',
    articulationConfig: {
      hasJeep: true,
      jeepAxles: 3,
      jeepLength: 5.0,
      hasSteerable: true,
      steerableAxles: 5,
      steerableLength: 8,
      jointType: 'pivot',
      maxArticulation: 60,
      offTrackingReduction: 0.70,
      tractorAxles: 2,
      trailerAxles: 2, // 11 - 2 - 3 - 5 = 1, min 2
    },
    overallDimensions: {
      overallLength: 39.9, // 8.0 + 5.0 + 8.0 + 18.9
      overallHeight: 4.1,
      transportWidth: 2.6,
      curbWeight: 65800,
    },
    segments: [
      {
        id: 'tractor',
        type: 'tractor',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetRear: 7.5,
        wheelbase: 4.5,
        fifthWheelOffset: 0.5,
        driveGroupSpread: 1.4,
      },
      {
        id: 'jeep',
        type: 'jeep_dolly',
        referenceLength: 5.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.3,
        couplerOffsetRear: 4.7,
        drawbarLength: 3.5,
      },
      {
        id: 'steerable',
        type: 'steerable_dolly',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        couplerOffsetRear: 7.5,
        drawbarLength: 6.5,
      },
      {
        id: 'trailer',
        type: 'trailer',
        referenceLength: 18.9,
        usableDeckLength: 18.9,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        kingpinSetback: 1.5,
        bogieSlideRange: 1.0,
      },
    ],
    axleGroups: [
      {
        segmentId: 'tractor',
        groupId: 'tractor-steer',
        positionFromSegmentFront: 0.5,
        axleCount: 1,
        spread: 0,
        steerable: true,
        loadShare: 0.08,
      },
      {
        segmentId: 'tractor',
        groupId: 'tractor-drive',
        positionFromSegmentFront: 5.5,
        axleCount: 2,
        spread: 1.4,
        steerable: false,
        loadShare: 0.16,
      },
      {
        segmentId: 'jeep',
        groupId: 'jeep-axles',
        positionFromSegmentFront: 2.4,
        axleCount: 3,
        spread: 2.6,
        steerable: false,
        loadShare: 0.20,
      },
      {
        segmentId: 'steerable',
        groupId: 'steerable-axles',
        positionFromSegmentFront: 4.0,
        axleCount: 5,
        spread: 5.2,
        steerable: true,
        loadShare: 0.34,
      },
      {
        segmentId: 'trailer',
        groupId: 'trailer-bogie',
        positionFromSegmentFront: 16.0,
        axleCount: 2,
        spread: 1.3,
        steerable: false,
        loadShare: 0.22,
      },
    ],
    articulationJoints: [
      {
        id: 'tractor-jeep-pivot',
        type: 'pivot',
        fromSegmentId: 'tractor',
        toSegmentId: 'jeep',
        positionOnFrom: 7.5,
        positionOnTo: 0.3,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'jeep-steerable-kingpin',
        type: 'king_pin',
        fromSegmentId: 'jeep',
        toSegmentId: 'steerable',
        positionOnFrom: 4.7,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'steerable-trailer-kingpin',
        type: 'king_pin',
        fromSegmentId: 'steerable',
        toSegmentId: 'trailer',
        positionOnFrom: 7.5,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
    ],
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '12axle-rgn',
    name: '12-Axle RGN',
    width: 2.6, // 8.5 ft
    height: 4.1, // Total envelope: deck 0.76m + cargo 3.34m = 4.1m (13.5 ft)
    length: 18.9, // 62 ft well max
    widthUnit: 'meters',
    heightUnit: 'meters',
    lengthUnit: 'meters',
    weightCapacity: 65800, // 145,000 lbs
    weightUnit: 'kg',
    axleConfiguration: '12 axles heavy RGN',
    description: 'Heavy multi-axle RGN, 45-62 ft well (deck height: 0.76m)',
    articulationConfig: {
      hasJeep: true,
      jeepAxles: 3,
      jeepLength: 5.0,
      hasSteerable: true,
      steerableAxles: 6,
      steerableLength: 8,
      jointType: 'pivot',
      maxArticulation: 60,
      offTrackingReduction: 0.70,
      tractorAxles: 2,
      trailerAxles: 2, // 12 - 2 - 3 - 6 = 1, min 2
    },
    overallDimensions: {
      overallLength: 39.9, // 8.0 + 5.0 + 8.0 + 18.9
      overallHeight: 4.1,
      transportWidth: 2.6,
      curbWeight: 65800,
    },
    segments: [
      {
        id: 'tractor',
        type: 'tractor',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetRear: 7.5,
        wheelbase: 4.5,
        fifthWheelOffset: 0.5,
        driveGroupSpread: 1.4,
      },
      {
        id: 'jeep',
        type: 'jeep_dolly',
        referenceLength: 5.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.3,
        couplerOffsetRear: 4.7,
        drawbarLength: 3.5,
      },
      {
        id: 'steerable',
        type: 'steerable_dolly',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        couplerOffsetRear: 7.5,
        drawbarLength: 6.5,
      },
      {
        id: 'trailer',
        type: 'trailer',
        referenceLength: 18.9,
        usableDeckLength: 18.9,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        kingpinSetback: 1.5,
        bogieSlideRange: 1.0,
      },
    ],
    axleGroups: [
      {
        segmentId: 'tractor',
        groupId: 'tractor-steer',
        positionFromSegmentFront: 0.5,
        axleCount: 1,
        spread: 0,
        steerable: true,
        loadShare: 0.07,
      },
      {
        segmentId: 'tractor',
        groupId: 'tractor-drive',
        positionFromSegmentFront: 5.5,
        axleCount: 2,
        spread: 1.4,
        steerable: false,
        loadShare: 0.15,
      },
      {
        segmentId: 'jeep',
        groupId: 'jeep-axles',
        positionFromSegmentFront: 2.4,
        axleCount: 3,
        spread: 2.6,
        steerable: false,
        loadShare: 0.20,
      },
      {
        segmentId: 'steerable',
        groupId: 'steerable-axles',
        positionFromSegmentFront: 4.0,
        axleCount: 6,
        spread: 6.5,
        steerable: true,
        loadShare: 0.36,
      },
      {
        segmentId: 'trailer',
        groupId: 'trailer-bogie',
        positionFromSegmentFront: 16.0,
        axleCount: 2,
        spread: 1.3,
        steerable: false,
        loadShare: 0.22,
      },
    ],
    articulationJoints: [
      {
        id: 'tractor-jeep-pivot',
        type: 'pivot',
        fromSegmentId: 'tractor',
        toSegmentId: 'jeep',
        positionOnFrom: 7.5,
        positionOnTo: 0.3,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'jeep-steerable-kingpin',
        type: 'king_pin',
        fromSegmentId: 'jeep',
        toSegmentId: 'steerable',
        positionOnFrom: 4.7,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'steerable-trailer-kingpin',
        type: 'king_pin',
        fromSegmentId: 'steerable',
        toSegmentId: 'trailer',
        positionOnFrom: 7.5,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
    ],
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
  // PERIMETER & BEAM TRAILERS
  {
    id: '7axle-perimeter',
    name: '7-Axle Perimeter',
    width: 6.1, // 20 ft expandable max
    height: 4.0, // Total envelope: deck 0.15m + oversized cargo 3.85m = 4.0m (13.1 ft)
    length: 18.3, // 60 ft deck
    widthUnit: 'meters',
    heightUnit: 'meters',
    lengthUnit: 'meters',
    weightCapacity: 40800, // 90,000 lbs
    weightUnit: 'kg',
    axleConfiguration: '7 axles perimeter frame',
    description: 'Perimeter frame, 10 ft expandable to 20 ft width (deck height: 0.15m)',
    articulationConfig: {
      hasJeep: true,
      jeepAxles: 3,
      jeepLength: 4.5,
      hasSteerable: false,
      jointType: 'pivot',
      maxArticulation: 60,
      tractorAxles: 2,
      trailerAxles: 2, // 7 - 2 - 3 = 2
    },
    overallDimensions: {
      overallLength: 30.8, // 8.0 + 4.5 + 18.3
      overallHeight: 4.0,
      transportWidth: 6.1,
      curbWeight: 40800,
    },
    segments: [
      {
        id: 'tractor',
        type: 'tractor',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetRear: 7.5,
        wheelbase: 4.5,
        fifthWheelOffset: 0.5,
        driveGroupSpread: 1.4,
      },
      {
        id: 'jeep',
        type: 'jeep_dolly',
        referenceLength: 4.5,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.3,
        couplerOffsetRear: 4.2,
        drawbarLength: 3.2,
      },
      {
        id: 'trailer',
        type: 'trailer',
        referenceLength: 18.3,
        usableDeckLength: 18.3,
        deckWidth: 6.1,
        maxWidth: 6.1,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        kingpinSetback: 1.5,
        bogieSlideRange: 1.0,
      },
    ],
    axleGroups: [
      {
        segmentId: 'tractor',
        groupId: 'tractor-steer',
        positionFromSegmentFront: 0.5,
        axleCount: 1,
        spread: 0,
        steerable: true,
        loadShare: 0.12,
      },
      {
        segmentId: 'tractor',
        groupId: 'tractor-drive',
        positionFromSegmentFront: 5.5,
        axleCount: 2,
        spread: 1.4,
        steerable: false,
        loadShare: 0.24,
      },
      {
        segmentId: 'jeep',
        groupId: 'jeep-axles',
        positionFromSegmentFront: 2.2,
        axleCount: 3,
        spread: 2.6,
        steerable: false,
        loadShare: 0.26,
      },
      {
        segmentId: 'trailer',
        groupId: 'trailer-bogie',
        positionFromSegmentFront: 15.5,
        axleCount: 2,
        spread: 1.3,
        steerable: false,
        loadShare: 0.38,
      },
    ],
    articulationJoints: [
      {
        id: 'tractor-jeep-pivot',
        type: 'pivot',
        fromSegmentId: 'tractor',
        toSegmentId: 'jeep',
        positionOnFrom: 7.5,
        positionOnTo: 0.3,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'jeep-trailer-kingpin',
        type: 'king_pin',
        fromSegmentId: 'jeep',
        toSegmentId: 'trailer',
        positionOnFrom: 4.2,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
    ],
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '8axle-perimeter',
    name: '8-Axle Perimeter',
    width: 6.1, // 20 ft expandable max
    height: 4.0, // Total envelope: deck 0.15m + oversized cargo 3.85m = 4.0m (13.1 ft)
    length: 18.3, // 60 ft deck
    widthUnit: 'meters',
    heightUnit: 'meters',
    lengthUnit: 'meters',
    weightCapacity: 49900, // 110,000 lbs
    weightUnit: 'kg',
    axleConfiguration: '8 axles perimeter frame',
    description: 'Perimeter frame, 10 ft expandable to 20 ft width (deck height: 0.15m)',
    articulationConfig: {
      hasJeep: true,
      jeepAxles: 3,
      jeepLength: 4.5,
      hasSteerable: false,
      jointType: 'pivot',
      maxArticulation: 60,
      tractorAxles: 2,
      trailerAxles: 3, // 8 - 2 - 3 = 3
    },
    overallDimensions: {
      overallLength: 30.8, // 8.0 + 4.5 + 18.3
      overallHeight: 4.0,
      transportWidth: 6.1,
      curbWeight: 49900,
    },
    segments: [
      {
        id: 'tractor',
        type: 'tractor',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetRear: 7.5,
        wheelbase: 4.5,
        fifthWheelOffset: 0.5,
        driveGroupSpread: 1.4,
      },
      {
        id: 'jeep',
        type: 'jeep_dolly',
        referenceLength: 4.5,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.3,
        couplerOffsetRear: 4.2,
        drawbarLength: 3.2,
      },
      {
        id: 'trailer',
        type: 'trailer',
        referenceLength: 18.3,
        usableDeckLength: 18.3,
        deckWidth: 6.1,
        maxWidth: 6.1,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        kingpinSetback: 1.5,
        bogieSlideRange: 1.0,
      },
    ],
    axleGroups: [
      {
        segmentId: 'tractor',
        groupId: 'tractor-steer',
        positionFromSegmentFront: 0.5,
        axleCount: 1,
        spread: 0,
        steerable: true,
        loadShare: 0.10,
      },
      {
        segmentId: 'tractor',
        groupId: 'tractor-drive',
        positionFromSegmentFront: 5.5,
        axleCount: 2,
        spread: 1.4,
        steerable: false,
        loadShare: 0.22,
      },
      {
        segmentId: 'jeep',
        groupId: 'jeep-axles',
        positionFromSegmentFront: 2.2,
        axleCount: 3,
        spread: 2.6,
        steerable: false,
        loadShare: 0.24,
      },
      {
        segmentId: 'trailer',
        groupId: 'trailer-bogie',
        positionFromSegmentFront: 15.0,
        axleCount: 3,
        spread: 2.6,
        steerable: false,
        loadShare: 0.44,
      },
    ],
    articulationJoints: [
      {
        id: 'tractor-jeep-pivot',
        type: 'pivot',
        fromSegmentId: 'tractor',
        toSegmentId: 'jeep',
        positionOnFrom: 7.5,
        positionOnTo: 0.3,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'jeep-trailer-kingpin',
        type: 'king_pin',
        fromSegmentId: 'jeep',
        toSegmentId: 'trailer',
        positionOnFrom: 4.2,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
    ],
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '11axle-perimeter',
    name: '11-Axle Perimeter',
    width: 6.1, // 20 ft expandable max
    height: 4.0, // Total envelope: deck 0.15m + oversized cargo 3.85m = 4.0m (13.1 ft)
    length: 25.9, // 85 ft deck
    widthUnit: 'meters',
    heightUnit: 'meters',
    lengthUnit: 'meters',
    weightCapacity: 77100, // 170,000 lbs
    weightUnit: 'kg',
    axleConfiguration: '11 axles perimeter frame',
    description: 'Wide perimeter frame, 10 ft expandable to 20 ft width (deck height: 0.15m)',
    articulationConfig: {
      hasJeep: true,
      jeepAxles: 3,
      jeepLength: 4.5,
      hasSteerable: true,
      steerableAxles: 6,
      steerableLength: 10,
      jointType: 'pivot',
      maxArticulation: 60,
      offTrackingReduction: 0.70,
      tractorAxles: 2,
      trailerAxles: 2, // 11 - 2 - 3 - 6 = 0, min 2
    },
    overallDimensions: {
      overallLength: 48.4, // 8.0 + 4.5 + 10.0 + 25.9
      overallHeight: 4.0,
      transportWidth: 6.1,
      curbWeight: 77100,
    },
    segments: [
      {
        id: 'tractor',
        type: 'tractor',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetRear: 7.5,
        wheelbase: 4.5,
        fifthWheelOffset: 0.5,
        driveGroupSpread: 1.4,
      },
      {
        id: 'jeep',
        type: 'jeep_dolly',
        referenceLength: 4.5,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.3,
        couplerOffsetRear: 4.2,
        drawbarLength: 3.2,
      },
      {
        id: 'steerable',
        type: 'steerable_dolly',
        referenceLength: 10.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        couplerOffsetRear: 9.5,
        drawbarLength: 8.0,
      },
      {
        id: 'trailer',
        type: 'trailer',
        referenceLength: 25.9,
        usableDeckLength: 25.9,
        deckWidth: 6.1,
        maxWidth: 6.1,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        kingpinSetback: 2.0,
        bogieSlideRange: 1.5,
      },
    ],
    axleGroups: [
      {
        segmentId: 'tractor',
        groupId: 'tractor-steer',
        positionFromSegmentFront: 0.5,
        axleCount: 1,
        spread: 0,
        steerable: true,
        loadShare: 0.08,
      },
      {
        segmentId: 'tractor',
        groupId: 'tractor-drive',
        positionFromSegmentFront: 5.5,
        axleCount: 2,
        spread: 1.4,
        steerable: false,
        loadShare: 0.16,
      },
      {
        segmentId: 'jeep',
        groupId: 'jeep-axles',
        positionFromSegmentFront: 2.2,
        axleCount: 3,
        spread: 2.6,
        steerable: false,
        loadShare: 0.20,
      },
      {
        segmentId: 'steerable',
        groupId: 'steerable-axles',
        positionFromSegmentFront: 5.0,
        axleCount: 6,
        spread: 6.5,
        steerable: true,
        loadShare: 0.34,
      },
      {
        segmentId: 'trailer',
        groupId: 'trailer-bogie',
        positionFromSegmentFront: 22.5,
        axleCount: 2,
        spread: 1.3,
        steerable: false,
        loadShare: 0.22,
      },
    ],
    articulationJoints: [
      {
        id: 'tractor-jeep-pivot',
        type: 'pivot',
        fromSegmentId: 'tractor',
        toSegmentId: 'jeep',
        positionOnFrom: 7.5,
        positionOnTo: 0.3,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'jeep-steerable-kingpin',
        type: 'king_pin',
        fromSegmentId: 'jeep',
        toSegmentId: 'steerable',
        positionOnFrom: 4.2,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'steerable-trailer-kingpin',
        type: 'king_pin',
        fromSegmentId: 'steerable',
        toSegmentId: 'trailer',
        positionOnFrom: 9.5,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
    ],
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '13axle-perimeter',
    name: '13-Axle Perimeter',
    width: 6.1, // 20 ft expandable max
    height: 4.2, // Total envelope: deck 0.36m + oversized cargo 3.84m = 4.2m (13.8 ft)
    length: 27.4, // 90 ft deck max
    widthUnit: 'meters',
    heightUnit: 'meters',
    lengthUnit: 'meters',
    weightCapacity: 90700, // 200,000 lbs
    weightUnit: 'kg',
    axleConfiguration: '13 axles perimeter frame air ride',
    description: 'Heavy perimeter frame, 10.2 ft expandable to 20 ft width (deck height: 0.36m)',
    articulationConfig: {
      hasJeep: true,
      jeepAxles: 3,
      jeepLength: 4.5,
      hasSteerable: true,
      steerableAxles: 8,
      steerableLength: 10,
      jointType: 'pivot',
      maxArticulation: 60,
      offTrackingReduction: 0.70,
      tractorAxles: 2,
      trailerAxles: 2, // 13 - 2 - 3 - 8 = 0, min 2
    },
    overallDimensions: {
      overallLength: 49.9, // 8.0 + 4.5 + 10.0 + 27.4
      overallHeight: 4.2,
      transportWidth: 6.1,
      curbWeight: 90700,
    },
    segments: [
      {
        id: 'tractor',
        type: 'tractor',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetRear: 7.5,
        wheelbase: 4.5,
        fifthWheelOffset: 0.5,
        driveGroupSpread: 1.4,
      },
      {
        id: 'jeep',
        type: 'jeep_dolly',
        referenceLength: 4.5,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.3,
        couplerOffsetRear: 4.2,
        drawbarLength: 3.2,
      },
      {
        id: 'steerable',
        type: 'steerable_dolly',
        referenceLength: 10.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        couplerOffsetRear: 9.5,
        drawbarLength: 8.0,
      },
      {
        id: 'trailer',
        type: 'trailer',
        referenceLength: 27.4,
        usableDeckLength: 27.4,
        deckWidth: 6.1,
        maxWidth: 6.1,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        kingpinSetback: 2.2,
        bogieSlideRange: 1.5,
      },
    ],
    axleGroups: [
      {
        segmentId: 'tractor',
        groupId: 'tractor-steer',
        positionFromSegmentFront: 0.5,
        axleCount: 1,
        spread: 0,
        steerable: true,
        loadShare: 0.07,
      },
      {
        segmentId: 'tractor',
        groupId: 'tractor-drive',
        positionFromSegmentFront: 5.5,
        axleCount: 2,
        spread: 1.4,
        steerable: false,
        loadShare: 0.14,
      },
      {
        segmentId: 'jeep',
        groupId: 'jeep-axles',
        positionFromSegmentFront: 2.2,
        axleCount: 3,
        spread: 2.6,
        steerable: false,
        loadShare: 0.18,
      },
      {
        segmentId: 'steerable',
        groupId: 'steerable-axles',
        positionFromSegmentFront: 5.0,
        axleCount: 8,
        spread: 9.1,
        steerable: true,
        loadShare: 0.40,
      },
      {
        segmentId: 'trailer',
        groupId: 'trailer-bogie',
        positionFromSegmentFront: 24.0,
        axleCount: 2,
        spread: 1.3,
        steerable: false,
        loadShare: 0.21,
      },
    ],
    articulationJoints: [
      {
        id: 'tractor-jeep-pivot',
        type: 'pivot',
        fromSegmentId: 'tractor',
        toSegmentId: 'jeep',
        positionOnFrom: 7.5,
        positionOnTo: 0.3,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'jeep-steerable-kingpin',
        type: 'king_pin',
        fromSegmentId: 'jeep',
        toSegmentId: 'steerable',
        positionOnFrom: 4.2,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'steerable-trailer-kingpin',
        type: 'king_pin',
        fromSegmentId: 'steerable',
        toSegmentId: 'trailer',
        positionOnFrom: 9.5,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
    ],
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'beam-trailer-13axle',
    name: 'Beam Trailer (13-Axle)',
    width: 3.0, // 10 ft
    height: 4.5, // Total envelope: deck 0.69m + tall beam cargo 3.81m = 4.5m (14.8 ft) for beams/girders
    length: 30.0, // 100 ft typical beam trailer length
    widthUnit: 'meters',
    heightUnit: 'meters',
    lengthUnit: 'meters',
    weightCapacity: 76200, // 168,000 lbs
    weightUnit: 'kg',
    axleConfiguration: '13 axles beam trailer',
    description: 'Beam/girder hauler, variable length custom (deck height: 0.69m)',
    articulationConfig: {
      hasJeep: true,
      jeepAxles: 3,
      jeepLength: 4.5,
      hasSteerable: true,
      steerableAxles: 8,
      steerableLength: 10,
      jointType: 'pivot',
      maxArticulation: 60,
      offTrackingReduction: 0.70,
      tractorAxles: 2,
      trailerAxles: 2, // 13 - 2 - 3 - 8 = 0, min 2
    },
    overallDimensions: {
      overallLength: 52.5, // 8.0 + 4.5 + 10.0 + 30.0
      overallHeight: 4.5,
      transportWidth: 3.0,
      curbWeight: 76200,
    },
    segments: [
      {
        id: 'tractor',
        type: 'tractor',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetRear: 7.5,
        wheelbase: 4.5,
        fifthWheelOffset: 0.5,
        driveGroupSpread: 1.4,
      },
      {
        id: 'jeep',
        type: 'jeep_dolly',
        referenceLength: 4.5,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.3,
        couplerOffsetRear: 4.2,
        drawbarLength: 3.2,
      },
      {
        id: 'steerable',
        type: 'steerable_dolly',
        referenceLength: 10.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        couplerOffsetRear: 9.5,
        drawbarLength: 8.0,
      },
      {
        id: 'trailer',
        type: 'trailer',
        referenceLength: 30.0,
        usableDeckLength: 30.0,
        deckWidth: 3.0,
        maxWidth: 3.0,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        kingpinSetback: 2.5,
        bogieSlideRange: 2.0,
      },
    ],
    axleGroups: [
      {
        segmentId: 'tractor',
        groupId: 'tractor-steer',
        positionFromSegmentFront: 0.5,
        axleCount: 1,
        spread: 0,
        steerable: true,
        loadShare: 0.07,
      },
      {
        segmentId: 'tractor',
        groupId: 'tractor-drive',
        positionFromSegmentFront: 5.5,
        axleCount: 2,
        spread: 1.4,
        steerable: false,
        loadShare: 0.14,
      },
      {
        segmentId: 'jeep',
        groupId: 'jeep-axles',
        positionFromSegmentFront: 2.2,
        axleCount: 3,
        spread: 2.6,
        steerable: false,
        loadShare: 0.18,
      },
      {
        segmentId: 'steerable',
        groupId: 'steerable-axles',
        positionFromSegmentFront: 5.0,
        axleCount: 8,
        spread: 9.1,
        steerable: true,
        loadShare: 0.40,
      },
      {
        segmentId: 'trailer',
        groupId: 'trailer-bogie',
        positionFromSegmentFront: 27.0,
        axleCount: 2,
        spread: 1.3,
        steerable: false,
        loadShare: 0.21,
      },
    ],
    articulationJoints: [
      {
        id: 'tractor-jeep-pivot',
        type: 'pivot',
        fromSegmentId: 'tractor',
        toSegmentId: 'jeep',
        positionOnFrom: 7.5,
        positionOnTo: 0.3,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'jeep-steerable-kingpin',
        type: 'king_pin',
        fromSegmentId: 'jeep',
        toSegmentId: 'steerable',
        positionOnFrom: 4.2,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'steerable-trailer-kingpin',
        type: 'king_pin',
        fromSegmentId: 'steerable',
        toSegmentId: 'trailer',
        positionOnFrom: 9.5,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
    ],
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
  // DUAL LANE CONFIGURATIONS
  {
    id: '16axle-dual-lane',
    name: '16-Axle Dual Lane',
    width: 6.1, // 20 ft total (two 10 ft lanes)
    height: 4.0, // Total envelope: deck 0.15m + cargo 3.85m = 4.0m (13.1 ft)
    length: 18.3, // 60 ft
    widthUnit: 'meters',
    heightUnit: 'meters',
    lengthUnit: 'meters',
    weightCapacity: 104300, // 230,000 lbs
    weightUnit: 'kg',
    axleConfiguration: '16 axles dual lane configuration',
    description: 'Side-by-side dual lane, two 10 ft lanes (deck height: 0.15m)',
    articulationConfig: {
      hasJeep: true,
      jeepAxles: 4,
      jeepLength: 6.0,
      hasSteerable: true,
      steerableAxles: 8,
      steerableLength: 12,
      jointType: 'pivot',
      maxArticulation: 60,
      offTrackingReduction: 0.70,
      tractorAxles: 2,
      trailerAxles: 2, // 16 - 2 - 4 - 8 = 2
    },
    overallDimensions: {
      overallLength: 44.3, // 8.0 + 6.0 + 12.0 + 18.3
      overallHeight: 4.0,
      transportWidth: 6.1,
      curbWeight: 104300,
    },
    segments: [
      {
        id: 'tractor',
        type: 'tractor',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetRear: 7.5,
        wheelbase: 4.5,
        fifthWheelOffset: 0.5,
        driveGroupSpread: 1.4,
      },
      {
        id: 'jeep',
        type: 'jeep_dolly',
        referenceLength: 6.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.3,
        couplerOffsetRear: 5.7,
        drawbarLength: 4.5,
      },
      {
        id: 'steerable',
        type: 'steerable_dolly',
        referenceLength: 12.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        couplerOffsetRear: 11.5,
        drawbarLength: 10.0,
      },
      {
        id: 'trailer',
        type: 'trailer',
        referenceLength: 18.3,
        usableDeckLength: 18.3,
        deckWidth: 6.1,
        maxWidth: 6.1,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        kingpinSetback: 1.8,
        bogieSlideRange: 1.2,
      },
    ],
    axleGroups: [
      {
        segmentId: 'tractor',
        groupId: 'tractor-steer',
        positionFromSegmentFront: 0.5,
        axleCount: 1,
        spread: 0,
        steerable: true,
        loadShare: 0.06,
      },
      {
        segmentId: 'tractor',
        groupId: 'tractor-drive',
        positionFromSegmentFront: 5.5,
        axleCount: 2,
        spread: 1.4,
        steerable: false,
        loadShare: 0.12,
      },
      {
        segmentId: 'jeep',
        groupId: 'jeep-axles',
        positionFromSegmentFront: 3.0,
        axleCount: 4,
        spread: 3.9,
        steerable: false,
        loadShare: 0.22,
      },
      {
        segmentId: 'steerable',
        groupId: 'steerable-axles',
        positionFromSegmentFront: 6.0,
        axleCount: 8,
        spread: 10.4,
        steerable: true,
        loadShare: 0.44,
      },
      {
        segmentId: 'trailer',
        groupId: 'trailer-bogie',
        positionFromSegmentFront: 15.5,
        axleCount: 2,
        spread: 1.3,
        steerable: false,
        loadShare: 0.16,
      },
    ],
    articulationJoints: [
      {
        id: 'tractor-jeep-pivot',
        type: 'pivot',
        fromSegmentId: 'tractor',
        toSegmentId: 'jeep',
        positionOnFrom: 7.5,
        positionOnTo: 0.3,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'jeep-steerable-kingpin',
        type: 'king_pin',
        fromSegmentId: 'jeep',
        toSegmentId: 'steerable',
        positionOnFrom: 5.7,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'steerable-trailer-kingpin',
        type: 'king_pin',
        fromSegmentId: 'steerable',
        toSegmentId: 'trailer',
        positionOnFrom: 11.5,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
    ],
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '19axle-dual-lane',
    name: '19-Axle Dual Lane',
    width: 6.1, // 20 ft total (two 10 ft lanes)
    height: 4.0, // Total envelope: deck 0.15m + cargo 3.85m = 4.0m (13.1 ft)
    length: 18.3, // 60 ft
    widthUnit: 'meters',
    heightUnit: 'meters',
    lengthUnit: 'meters',
    weightCapacity: 129300, // 285,000 lbs
    weightUnit: 'kg',
    axleConfiguration: '19 axles dual lane heavy configuration',
    description: 'Heavy dual lane, two 10 ft lanes (deck height: 0.15m)',
    articulationConfig: {
      hasJeep: true,
      jeepAxles: 5,
      jeepLength: 8.0,
      hasSteerable: true,
      steerableAxles: 10,
      steerableLength: 15,
      jointType: 'pivot',
      maxArticulation: 60,
      offTrackingReduction: 0.70,
      tractorAxles: 2,
      trailerAxles: 2, // 19 - 2 - 5 - 10 = 2
    },
    overallDimensions: {
      overallLength: 49.3, // 8.0 + 8.0 + 15.0 + 18.3
      overallHeight: 4.0,
      transportWidth: 6.1,
      curbWeight: 129300,
    },
    segments: [
      {
        id: 'tractor',
        type: 'tractor',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetRear: 7.5,
        wheelbase: 4.5,
        fifthWheelOffset: 0.5,
        driveGroupSpread: 1.4,
      },
      {
        id: 'jeep',
        type: 'jeep_dolly',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.3,
        couplerOffsetRear: 7.7,
        drawbarLength: 6.0,
      },
      {
        id: 'steerable',
        type: 'steerable_dolly',
        referenceLength: 15.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        couplerOffsetRear: 14.5,
        drawbarLength: 12.5,
      },
      {
        id: 'trailer',
        type: 'trailer',
        referenceLength: 18.3,
        usableDeckLength: 18.3,
        deckWidth: 6.1,
        maxWidth: 6.1,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        kingpinSetback: 1.8,
        bogieSlideRange: 1.2,
      },
    ],
    axleGroups: [
      {
        segmentId: 'tractor',
        groupId: 'tractor-steer',
        positionFromSegmentFront: 0.5,
        axleCount: 1,
        spread: 0,
        steerable: true,
        loadShare: 0.05,
      },
      {
        segmentId: 'tractor',
        groupId: 'tractor-drive',
        positionFromSegmentFront: 5.5,
        axleCount: 2,
        spread: 1.4,
        steerable: false,
        loadShare: 0.10,
      },
      {
        segmentId: 'jeep',
        groupId: 'jeep-axles',
        positionFromSegmentFront: 4.0,
        axleCount: 5,
        spread: 5.2,
        steerable: false,
        loadShare: 0.24,
      },
      {
        segmentId: 'steerable',
        groupId: 'steerable-axles',
        positionFromSegmentFront: 7.5,
        axleCount: 10,
        spread: 13.0,
        steerable: true,
        loadShare: 0.46,
      },
      {
        segmentId: 'trailer',
        groupId: 'trailer-bogie',
        positionFromSegmentFront: 15.5,
        axleCount: 2,
        spread: 1.3,
        steerable: false,
        loadShare: 0.15,
      },
    ],
    articulationJoints: [
      {
        id: 'tractor-jeep-pivot',
        type: 'pivot',
        fromSegmentId: 'tractor',
        toSegmentId: 'jeep',
        positionOnFrom: 7.5,
        positionOnTo: 0.3,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'jeep-steerable-kingpin',
        type: 'king_pin',
        fromSegmentId: 'jeep',
        toSegmentId: 'steerable',
        positionOnFrom: 7.7,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'steerable-trailer-kingpin',
        type: 'king_pin',
        fromSegmentId: 'steerable',
        toSegmentId: 'trailer',
        positionOnFrom: 14.5,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
    ],
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
  // SCHNABEL & SPECIALIZED
  {
    id: '13axle-schnabel',
    name: '13-Axle Schnabel',
    width: 3.0, // 10 ft
    height: 4.3, // Typical envelope for heavy transformers/machinery on schnabel = 4.3m (14.1 ft)
    length: 30.5, // 100 ft between goosenecks max
    frontOverhang: 6.1, // 20 ft max
    rearOverhang: 6.1, // 20 ft max
    widthUnit: 'meters',
    heightUnit: 'meters',
    lengthUnit: 'meters',
    frontOverhangUnit: 'meters',
    rearOverhangUnit: 'meters',
    weightCapacity: 83900, // 185,000 lbs
    weightUnit: 'kg',
    axleConfiguration: '13 axles double schnabel with steerable dolly',
    description: 'Double gooseneck schnabel with 3-axle jeep + 6-axle steer dolly (variable self-supporting height)',
    articulationConfig: {
      hasJeep: true,
      jeepAxles: 6,
      jeepLength: 10.0,
      hasSteerable: true,
      steerableAxles: 6,
      steerableLength: 12,
      jointType: 'king_pin',
      maxArticulation: 60,
      offTrackingReduction: 0.70,
      tractorAxles: 2,
      trailerAxles: 2, // 13 - 2 - 6 - 6 = -1, min 2
    },
    overallDimensions: {
      overallLength: 60.5, // 8.0 + 10.0 + 12.0 + 30.5
      overallHeight: 4.3,
      transportWidth: 3.0,
      curbWeight: 83900,
    },
    segments: [
      {
        id: 'tractor',
        type: 'tractor',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetRear: 7.5,
        wheelbase: 4.5,
        fifthWheelOffset: 0.5,
        driveGroupSpread: 1.4,
      },
      {
        id: 'jeep',
        type: 'jeep_dolly',
        referenceLength: 10.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.3,
        couplerOffsetRear: 9.7,
        drawbarLength: 8.0,
      },
      {
        id: 'steerable',
        type: 'steerable_dolly',
        referenceLength: 12.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        couplerOffsetRear: 11.5,
        drawbarLength: 10.0,
      },
      {
        id: 'trailer',
        type: 'trailer',
        referenceLength: 30.5,
        usableDeckLength: 30.5,
        deckWidth: 3.0,
        maxWidth: 3.0,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        kingpinSetback: 3.0,
        bogieSlideRange: 2.5,
      },
    ],
    axleGroups: [
      {
        segmentId: 'tractor',
        groupId: 'tractor-steer',
        positionFromSegmentFront: 0.5,
        axleCount: 1,
        spread: 0,
        steerable: true,
        loadShare: 0.07,
      },
      {
        segmentId: 'tractor',
        groupId: 'tractor-drive',
        positionFromSegmentFront: 5.5,
        axleCount: 2,
        spread: 1.4,
        steerable: false,
        loadShare: 0.14,
      },
      {
        segmentId: 'jeep',
        groupId: 'jeep-axles',
        positionFromSegmentFront: 5.0,
        axleCount: 6,
        spread: 6.5,
        steerable: false,
        loadShare: 0.32,
      },
      {
        segmentId: 'steerable',
        groupId: 'steerable-axles',
        positionFromSegmentFront: 6.0,
        axleCount: 6,
        spread: 6.5,
        steerable: true,
        loadShare: 0.30,
      },
      {
        segmentId: 'trailer',
        groupId: 'trailer-bogie',
        positionFromSegmentFront: 27.5,
        axleCount: 2,
        spread: 1.3,
        steerable: false,
        loadShare: 0.17,
      },
    ],
    articulationJoints: [
      {
        id: 'tractor-jeep-pivot',
        type: 'pivot',
        fromSegmentId: 'tractor',
        toSegmentId: 'jeep',
        positionOnFrom: 7.5,
        positionOnTo: 0.3,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'jeep-steerable-kingpin',
        type: 'king_pin',
        fromSegmentId: 'jeep',
        toSegmentId: 'steerable',
        positionOnFrom: 9.7,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'steerable-trailer-kingpin',
        type: 'king_pin',
        fromSegmentId: 'steerable',
        toSegmentId: 'trailer',
        positionOnFrom: 11.5,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
    ],
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '19axle-schnabel',
    name: '19-Axle Schnabel',
    width: 3.0, // 10 ft
    height: 4.5, // Typical envelope for extra-heavy loads on schnabel = 4.5m (14.8 ft)
    length: 30.5, // 100+ ft between goosenecks
    frontOverhang: 7.6, // 25 ft max
    rearOverhang: 7.6, // 25 ft max
    widthUnit: 'meters',
    heightUnit: 'meters',
    lengthUnit: 'meters',
    frontOverhangUnit: 'meters',
    rearOverhangUnit: 'meters',
    weightCapacity: 90700, // 200,000+ lbs
    weightUnit: 'kg',
    axleConfiguration: '19 axles heavy schnabel configuration',
    description: 'Heavy double schnabel, 100+ ft between goosenecks (variable self-supporting height)',
    articulationConfig: {
      hasJeep: true,
      jeepAxles: 8,
      jeepLength: 12.0,
      hasSteerable: true,
      steerableAxles: 8,
      steerableLength: 15,
      jointType: 'king_pin',
      maxArticulation: 60,
      offTrackingReduction: 0.70,
      tractorAxles: 2,
      trailerAxles: 2, // 19 - 2 - 8 - 8 = 1, min 2
    },
    overallDimensions: {
      overallLength: 65.5, // 8.0 + 12.0 + 15.0 + 30.5
      overallHeight: 4.5,
      transportWidth: 3.0,
      curbWeight: 90700,
    },
    segments: [
      {
        id: 'tractor',
        type: 'tractor',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetRear: 7.5,
        wheelbase: 4.5,
        fifthWheelOffset: 0.5,
        driveGroupSpread: 1.4,
      },
      {
        id: 'jeep',
        type: 'jeep_dolly',
        referenceLength: 12.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.3,
        couplerOffsetRear: 11.7,
        drawbarLength: 10.0,
      },
      {
        id: 'steerable',
        type: 'steerable_dolly',
        referenceLength: 15.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        couplerOffsetRear: 14.5,
        drawbarLength: 12.5,
      },
      {
        id: 'trailer',
        type: 'trailer',
        referenceLength: 30.5,
        usableDeckLength: 30.5,
        deckWidth: 3.0,
        maxWidth: 3.0,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        kingpinSetback: 3.0,
        bogieSlideRange: 2.5,
      },
    ],
    axleGroups: [
      {
        segmentId: 'tractor',
        groupId: 'tractor-steer',
        positionFromSegmentFront: 0.5,
        axleCount: 1,
        spread: 0,
        steerable: true,
        loadShare: 0.05,
      },
      {
        segmentId: 'tractor',
        groupId: 'tractor-drive',
        positionFromSegmentFront: 5.5,
        axleCount: 2,
        spread: 1.4,
        steerable: false,
        loadShare: 0.10,
      },
      {
        segmentId: 'jeep',
        groupId: 'jeep-axles',
        positionFromSegmentFront: 6.0,
        axleCount: 8,
        spread: 9.1,
        steerable: false,
        loadShare: 0.36,
      },
      {
        segmentId: 'steerable',
        groupId: 'steerable-axles',
        positionFromSegmentFront: 7.5,
        axleCount: 8,
        spread: 9.1,
        steerable: true,
        loadShare: 0.34,
      },
      {
        segmentId: 'trailer',
        groupId: 'trailer-bogie',
        positionFromSegmentFront: 27.5,
        axleCount: 2,
        spread: 1.3,
        steerable: false,
        loadShare: 0.15,
      },
    ],
    articulationJoints: [
      {
        id: 'tractor-jeep-pivot',
        type: 'pivot',
        fromSegmentId: 'tractor',
        toSegmentId: 'jeep',
        positionOnFrom: 7.5,
        positionOnTo: 0.3,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'jeep-steerable-kingpin',
        type: 'king_pin',
        fromSegmentId: 'jeep',
        toSegmentId: 'steerable',
        positionOnFrom: 11.7,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'steerable-trailer-kingpin',
        type: 'king_pin',
        fromSegmentId: 'steerable',
        toSegmentId: 'trailer',
        positionOnFrom: 14.5,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
    ],
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
  // SPECIALIZED WIND ENERGY
  {
    id: 'blade-trailer-schnabel',
    name: 'Blade Trailer',
    width: 3.0, // 10 ft max
    height: 5.0, // Wind blades with pivot can reach 5.0m (16.4 ft) when raised
    length: 54.9, // 180 ft max
    widthUnit: 'meters',
    heightUnit: 'meters',
    lengthUnit: 'meters',
    weightCapacity: 22700, // 50,000 lbs
    weightUnit: 'kg',
    axleConfiguration: 'Multi-axle blade trailer with pivot system',
    description: 'Specialized wind blade schnabel, 130-180 ft (variable pivot height)',
    articulationConfig: {
      hasJeep: true,
      jeepAxles: 3,
      jeepLength: 5.0,
      hasSteerable: true,
      steerableAxles: 4,
      steerableLength: 8,
      jointType: 'pivot',
      maxArticulation: 60,
      offTrackingReduction: 0.70,
      tractorAxles: 2,
      trailerAxles: 2, // No number in axleConfiguration, assume typical 2
    },
    overallDimensions: {
      overallLength: 75.9, // 8.0 + 5.0 + 8.0 + 54.9
      overallHeight: 5.0,
      transportWidth: 3.0,
      curbWeight: 22700,
    },
    segments: [
      {
        id: 'tractor',
        type: 'tractor',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetRear: 7.5,
        wheelbase: 4.5,
        fifthWheelOffset: 0.5,
        driveGroupSpread: 1.4,
      },
      {
        id: 'jeep',
        type: 'jeep_dolly',
        referenceLength: 5.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.3,
        couplerOffsetRear: 4.7,
        drawbarLength: 3.5,
      },
      {
        id: 'steerable',
        type: 'steerable_dolly',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        couplerOffsetRear: 7.5,
        drawbarLength: 6.5,
      },
      {
        id: 'trailer',
        type: 'trailer',
        referenceLength: 54.9,
        usableDeckLength: 54.9,
        deckWidth: 3.0,
        maxWidth: 3.0,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        kingpinSetback: 5.0,
        bogieSlideRange: 3.0,
      },
    ],
    axleGroups: [
      {
        segmentId: 'tractor',
        groupId: 'tractor-steer',
        positionFromSegmentFront: 0.5,
        axleCount: 1,
        spread: 0,
        steerable: true,
        loadShare: 0.08,
      },
      {
        segmentId: 'tractor',
        groupId: 'tractor-drive',
        positionFromSegmentFront: 5.5,
        axleCount: 2,
        spread: 1.4,
        steerable: false,
        loadShare: 0.16,
      },
      {
        segmentId: 'jeep',
        groupId: 'jeep-axles',
        positionFromSegmentFront: 2.4,
        axleCount: 3,
        spread: 2.6,
        steerable: false,
        loadShare: 0.22,
      },
      {
        segmentId: 'steerable',
        groupId: 'steerable-axles',
        positionFromSegmentFront: 4.0,
        axleCount: 4,
        spread: 3.9,
        steerable: true,
        loadShare: 0.28,
      },
      {
        segmentId: 'trailer',
        groupId: 'trailer-bogie',
        positionFromSegmentFront: 51.5,
        axleCount: 2,
        spread: 1.3,
        steerable: false,
        loadShare: 0.26,
      },
    ],
    articulationJoints: [
      {
        id: 'tractor-jeep-pivot',
        type: 'pivot',
        fromSegmentId: 'tractor',
        toSegmentId: 'jeep',
        positionOnFrom: 7.5,
        positionOnTo: 0.3,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'jeep-steerable-kingpin',
        type: 'king_pin',
        fromSegmentId: 'jeep',
        toSegmentId: 'steerable',
        positionOnFrom: 4.7,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'steerable-trailer-kingpin',
        type: 'king_pin',
        fromSegmentId: 'steerable',
        toSegmentId: 'trailer',
        positionOnFrom: 7.5,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
    ],
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tower-trailer',
    name: 'Tower Trailer',
    width: 2.6, // 8.5 ft
    height: 5.5, // Wind tower sections with deck can reach 5.5m (18 ft) total
    length: 44.2, // 145 ft extended max
    frontOverhang: 4.6, // 15 ft max
    rearOverhang: 6.1, // 20 ft max
    widthUnit: 'meters',
    heightUnit: 'meters',
    lengthUnit: 'meters',
    frontOverhangUnit: 'meters',
    rearOverhangUnit: 'meters',
    weightCapacity: 45400, // 100,000 lbs
    weightUnit: 'kg',
    axleConfiguration: 'Multi-axle extendable tower trailer',
    description: 'Extendable for wind tower sections, 110-145 ft (deck height: 1.5m)',
    articulationConfig: {
      hasJeep: true,
      jeepAxles: 2,
      jeepLength: 4.0,
      hasSteerable: false,
      jointType: 'fifth_wheel',
      maxArticulation: 45,
      tractorAxles: 2,
      trailerAxles: 2, // No number in axleConfiguration, assume typical 2
    },
    overallDimensions: {
      overallLength: 56.2, // 8.0 + 4.0 + 44.2
      overallHeight: 5.5,
      transportWidth: 2.6,
      curbWeight: 45400,
    },
    segments: [
      {
        id: 'tractor',
        type: 'tractor',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetRear: 7.5,
        wheelbase: 4.5,
        fifthWheelOffset: 0.5,
        driveGroupSpread: 1.4,
      },
      {
        id: 'jeep',
        type: 'jeep_dolly',
        referenceLength: 4.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.3,
        couplerOffsetRear: 3.7,
        drawbarLength: 2.8,
      },
      {
        id: 'trailer',
        type: 'trailer',
        referenceLength: 44.2,
        usableDeckLength: 44.2,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        kingpinSetback: 4.0,
        bogieSlideRange: 3.5,
      },
    ],
    axleGroups: [
      {
        segmentId: 'tractor',
        groupId: 'tractor-steer',
        positionFromSegmentFront: 0.5,
        axleCount: 1,
        spread: 0,
        steerable: true,
        loadShare: 0.14,
      },
      {
        segmentId: 'tractor',
        groupId: 'tractor-drive',
        positionFromSegmentFront: 5.5,
        axleCount: 2,
        spread: 1.4,
        steerable: false,
        loadShare: 0.28,
      },
      {
        segmentId: 'jeep',
        groupId: 'jeep-axles',
        positionFromSegmentFront: 2.0,
        axleCount: 2,
        spread: 1.3,
        steerable: false,
        loadShare: 0.22,
      },
      {
        segmentId: 'trailer',
        groupId: 'trailer-bogie',
        positionFromSegmentFront: 41.0,
        axleCount: 2,
        spread: 1.3,
        steerable: false,
        loadShare: 0.36,
      },
    ],
    articulationJoints: [
      {
        id: 'tractor-jeep-fifth-wheel',
        type: 'fifth_wheel',
        fromSegmentId: 'tractor',
        toSegmentId: 'jeep',
        positionOnFrom: 7.5,
        positionOnTo: 0.3,
        maxPitch: 12,
        maxYaw: 45,
        lateralOffset: 0,
      },
      {
        id: 'jeep-trailer-kingpin',
        type: 'king_pin',
        fromSegmentId: 'jeep',
        toSegmentId: 'trailer',
        positionOnFrom: 3.7,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
    ],
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
  // MODULAR COMBINATIONS
  {
    id: 'jeep-dolly-trailer-13axle',
    name: 'Jeep + Dolly + Trailer (13-Axle)',
    width: 3.0, // 10 ft
    height: 4.1, // Total envelope: deck 0.76m + cargo 3.34m = 4.1m (13.5 ft)
    length: 36.6, // 120 ft total max
    frontOverhang: 4.6, // 15 ft
    rearOverhang: 4.6, // 15 ft
    widthUnit: 'meters',
    heightUnit: 'meters',
    lengthUnit: 'meters',
    frontOverhangUnit: 'meters',
    rearOverhangUnit: 'meters',
    weightCapacity: 86200, // 190,000 lbs
    weightUnit: 'kg',
    axleConfiguration: '13 axles: 3 jeep + 6 steerable dolly + 4 trailer',
    description: '2+1 jeep, steerable dolly, trailer, 100-120 ft total (deck height: 0.76m)',
    articulationConfig: {
      hasJeep: true,
      jeepAxles: 3,
      jeepLength: 5.0,
      hasSteerable: true,
      steerableAxles: 6,
      steerableLength: 12,
      jointType: 'pivot',
      maxArticulation: 60,
      offTrackingReduction: 0.70,
      tractorAxles: 2,
      trailerAxles: 2, // 13 - 2 - 3 - 6 = 2
    },
    overallDimensions: {
      overallLength: 61.6, // 8.0 + 5.0 + 12.0 + 36.6
      overallHeight: 4.1,
      transportWidth: 3.0,
      curbWeight: 86200,
    },
    segments: [
      {
        id: 'tractor',
        type: 'tractor',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetRear: 7.5,
        wheelbase: 4.5,
        fifthWheelOffset: 0.5,
        driveGroupSpread: 1.4,
      },
      {
        id: 'jeep',
        type: 'jeep_dolly',
        referenceLength: 5.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.3,
        couplerOffsetRear: 4.7,
        drawbarLength: 3.5,
      },
      {
        id: 'steerable',
        type: 'steerable_dolly',
        referenceLength: 12.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        couplerOffsetRear: 11.5,
        drawbarLength: 10.0,
      },
      {
        id: 'trailer',
        type: 'trailer',
        referenceLength: 36.6,
        usableDeckLength: 36.6,
        deckWidth: 3.0,
        maxWidth: 3.0,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        kingpinSetback: 3.5,
        bogieSlideRange: 2.5,
      },
    ],
    axleGroups: [
      {
        segmentId: 'tractor',
        groupId: 'tractor-steer',
        positionFromSegmentFront: 0.5,
        axleCount: 1,
        spread: 0,
        steerable: true,
        loadShare: 0.07,
      },
      {
        segmentId: 'tractor',
        groupId: 'tractor-drive',
        positionFromSegmentFront: 5.5,
        axleCount: 2,
        spread: 1.4,
        steerable: false,
        loadShare: 0.14,
      },
      {
        segmentId: 'jeep',
        groupId: 'jeep-axles',
        positionFromSegmentFront: 2.4,
        axleCount: 3,
        spread: 2.6,
        steerable: false,
        loadShare: 0.20,
      },
      {
        segmentId: 'steerable',
        groupId: 'steerable-axles',
        positionFromSegmentFront: 6.0,
        axleCount: 6,
        spread: 6.5,
        steerable: true,
        loadShare: 0.32,
      },
      {
        segmentId: 'trailer',
        groupId: 'trailer-bogie',
        positionFromSegmentFront: 33.5,
        axleCount: 2,
        spread: 1.3,
        steerable: false,
        loadShare: 0.27,
      },
    ],
    articulationJoints: [
      {
        id: 'tractor-jeep-pivot',
        type: 'pivot',
        fromSegmentId: 'tractor',
        toSegmentId: 'jeep',
        positionOnFrom: 7.5,
        positionOnTo: 0.3,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'jeep-steerable-kingpin',
        type: 'king_pin',
        fromSegmentId: 'jeep',
        toSegmentId: 'steerable',
        positionOnFrom: 4.7,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'steerable-trailer-kingpin',
        type: 'king_pin',
        fromSegmentId: 'steerable',
        toSegmentId: 'trailer',
        positionOnFrom: 11.5,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
    ],
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '19-22axle-modular',
    name: '19-22 Axle Modular',
    width: 4.9, // 16 ft max
    height: 4.0, // Total envelope: deck 0.61m + cargo 3.4m = 4.0m (13.1 ft)
    length: 45.7, // 150 ft total max
    frontOverhang: 9.1, // 30 ft max
    rearOverhang: 9.1, // 30 ft max
    widthUnit: 'meters',
    heightUnit: 'meters',
    lengthUnit: 'meters',
    frontOverhangUnit: 'meters',
    rearOverhangUnit: 'meters',
    weightCapacity: 158800, // 350,000 lbs
    weightUnit: 'kg',
    axleConfiguration: '19-22 axles specialized modular combination',
    description: 'Multi-jeep and dolly combination, 120-150 ft total (deck height: 0.61m)',
    articulationConfig: {
      hasJeep: true,
      jeepAxles: 8,
      jeepLength: 15.0,
      hasSteerable: true,
      steerableAxles: 10,
      steerableLength: 15,
      jointType: 'pivot',
      maxArticulation: 60,
      offTrackingReduction: 0.70,
      tractorAxles: 2,
      trailerAxles: 2, // 19 - 2 - 8 - 10 = -1, min 2 (or using 22: 22 - 2 - 8 - 10 = 2)
    },
    overallDimensions: {
      overallLength: 83.7, // 8.0 + 15.0 + 15.0 + 45.7
      overallHeight: 4.0,
      transportWidth: 4.9,
      curbWeight: 158800,
    },
    segments: [
      {
        id: 'tractor',
        type: 'tractor',
        referenceLength: 8.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetRear: 7.5,
        wheelbase: 4.5,
        fifthWheelOffset: 0.5,
        driveGroupSpread: 1.4,
      },
      {
        id: 'jeep',
        type: 'jeep_dolly',
        referenceLength: 15.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.3,
        couplerOffsetRear: 14.7,
        drawbarLength: 12.5,
      },
      {
        id: 'steerable',
        type: 'steerable_dolly',
        referenceLength: 15.0,
        deckWidth: 2.6,
        maxWidth: 2.6,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        couplerOffsetRear: 14.5,
        drawbarLength: 12.5,
      },
      {
        id: 'trailer',
        type: 'trailer',
        referenceLength: 45.7,
        usableDeckLength: 45.7,
        deckWidth: 4.9,
        maxWidth: 4.9,
        trackWidth: 2.4,
        couplerOffsetFront: 0.5,
        kingpinSetback: 4.5,
        bogieSlideRange: 3.5,
      },
    ],
    axleGroups: [
      {
        segmentId: 'tractor',
        groupId: 'tractor-steer',
        positionFromSegmentFront: 0.5,
        axleCount: 1,
        spread: 0,
        steerable: true,
        loadShare: 0.04,
      },
      {
        segmentId: 'tractor',
        groupId: 'tractor-drive',
        positionFromSegmentFront: 5.5,
        axleCount: 2,
        spread: 1.4,
        steerable: false,
        loadShare: 0.08,
      },
      {
        segmentId: 'jeep',
        groupId: 'jeep-axles',
        positionFromSegmentFront: 7.5,
        axleCount: 8,
        spread: 10.4,
        steerable: false,
        loadShare: 0.34,
      },
      {
        segmentId: 'steerable',
        groupId: 'steerable-axles',
        positionFromSegmentFront: 7.5,
        axleCount: 10,
        spread: 13.0,
        steerable: true,
        loadShare: 0.40,
      },
      {
        segmentId: 'trailer',
        groupId: 'trailer-bogie',
        positionFromSegmentFront: 42.5,
        axleCount: 2,
        spread: 1.3,
        steerable: false,
        loadShare: 0.14,
      },
    ],
    articulationJoints: [
      {
        id: 'tractor-jeep-pivot',
        type: 'pivot',
        fromSegmentId: 'tractor',
        toSegmentId: 'jeep',
        positionOnFrom: 7.5,
        positionOnTo: 0.3,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'jeep-steerable-kingpin',
        type: 'king_pin',
        fromSegmentId: 'jeep',
        toSegmentId: 'steerable',
        positionOnFrom: 14.7,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
      {
        id: 'steerable-trailer-kingpin',
        type: 'king_pin',
        fromSegmentId: 'steerable',
        toSegmentId: 'trailer',
        positionOnFrom: 14.5,
        positionOnTo: 0.5,
        maxPitch: 15,
        maxYaw: 60,
        lateralOffset: 0,
      },
    ],
    isDefault: false,
    createdAt: new Date().toISOString(),
  },
];

interface EnvelopeStore {
  // State
  version: number;
  profiles: VehicleProfile[];
  settings: EnvelopeSettings;
  violations: ClearanceViolation[];
  isMonitoring: boolean;
  
  // Profile Management
  addProfile: (profile: Omit<VehicleProfile, 'id' | 'createdAt'>) => void;
  updateProfile: (id: string, updates: Partial<VehicleProfile>) => void;
  deleteProfile: (id: string) => void;
  getActiveProfile: () => VehicleProfile | null;
  switchProfile: (profileId: string) => void;
  
  // Settings Management
  updateSettings: (updates: Partial<EnvelopeSettings>) => void;
  toggleEnabled: () => void;
  toggleAudio: () => void;
  toggleVisual: () => void;
  
  // Violation Logging
  logViolation: (violation: Omit<ClearanceViolation, 'id'>) => void;
  clearViolations: () => void;
  deleteViolation: (id: string) => void;
  getViolationsByProfile: (profileId: string) => ClearanceViolation[];
  
  // Monitoring Control
  startMonitoring: () => void;
  stopMonitoring: () => void;
  
  // Reset
  resetToDefaults: () => void;
}

export const useEnvelopeStore = create<EnvelopeStore>()(
  persist(
    (set, get) => ({
      // Initial State
      version: 2, // Version 2: 25 OS/OW profiles with corrected envelope heights
      profiles: DEFAULT_PROFILES,
      settings: {
        enabled: false,
        activeProfileId: 'standard-flatbed-5axle',
        warningThreshold: 0.5, // meters
        criticalThreshold: 0.2, // meters
        audioEnabled: true,
        visualEnabled: true,
        lateralLasersEnabled: false,
      },
      violations: [],
      isMonitoring: false,
      
      // Profile Management
      addProfile: (profileData) => {
        const newProfile: VehicleProfile = {
          ...profileData,
          id: `custom-${Date.now()}`,
          createdAt: new Date().toISOString(),
          isDefault: false,
        };
        
        set((state) => ({
          profiles: [...state.profiles, newProfile],
        }));
      },
      
      updateProfile: (id, updates) => {
        set((state) => ({
          profiles: state.profiles.map(profile =>
            profile.id === id ? { ...profile, ...updates } : profile
          ),
        }));
      },
      
      deleteProfile: (id) => {
        set((state) => {
          const profile = state.profiles.find(p => p.id === id);
          if (profile?.isDefault) {
            return state;
          }
          
          // If deleting active profile, switch to first default
          const newActiveId = state.settings.activeProfileId === id
            ? state.profiles.find(p => p.isDefault)?.id || null
            : state.settings.activeProfileId;
          
          return {
            profiles: state.profiles.filter(p => p.id !== id),
            settings: {
              ...state.settings,
              activeProfileId: newActiveId,
            },
          };
        });
      },
      
      getActiveProfile: () => {
        const state = get();
        return state.profiles.find(p => p.id === state.settings.activeProfileId) || null;
      },
      
      switchProfile: (profileId) => {
        set((state) => ({
          settings: {
            ...state.settings,
            activeProfileId: profileId,
          },
        }));
      },
      
      // Settings Management
      updateSettings: (updates) => {
        set((state) => ({
          settings: {
            ...state.settings,
            ...updates,
          },
        }));
      },
      
      toggleEnabled: () => {
        set((state) => {
          const newEnabled = !state.settings.enabled;
          return {
            settings: {
              ...state.settings,
              enabled: newEnabled,
            },
            isMonitoring: newEnabled,
          };
        });
      },
      
      toggleAudio: () => {
        set((state) => ({
          settings: {
            ...state.settings,
            audioEnabled: !state.settings.audioEnabled,
          },
        }));
      },
      
      toggleVisual: () => {
        set((state) => ({
          settings: {
            ...state.settings,
            visualEnabled: !state.settings.visualEnabled,
          },
        }));
      },
      
      // Violation Logging
      logViolation: (violationData) => {
        const violation: ClearanceViolation = {
          ...violationData,
          id: `violation-${Date.now()}`,
        };
        
        set((state) => ({
          violations: [...state.violations, violation],
        }));
        
        // Dispatch custom event for other components
        window.dispatchEvent(new CustomEvent('envelope-violation', { detail: violation }));
      },
      
      clearViolations: () => {
        set({ violations: [] });
      },
      
      deleteViolation: (id) => {
        set((state) => ({
          violations: state.violations.filter(v => v.id !== id),
        }));
      },
      
      getViolationsByProfile: (profileId) => {
        const state = get();
        return state.violations.filter(v => v.profileId === profileId);
      },
      
      // Monitoring Control
      startMonitoring: () => {
        set({ isMonitoring: true });
      },
      
      stopMonitoring: () => {
        set({ isMonitoring: false });
      },
      
      // Reset
      resetToDefaults: () => {
        set({
          version: 2,
          profiles: DEFAULT_PROFILES,
          settings: {
            enabled: false,
            activeProfileId: 'standard-flatbed-5axle',
            warningThreshold: 0.5,
            criticalThreshold: 0.2,
            audioEnabled: true,
            visualEnabled: true,
            lateralLasersEnabled: false,
          },
          violations: [],
          isMonitoring: false,
        });
      },
    }),
    {
      name: 'envelope-clearance-storage',
      version: 2,
      migrate: (persistedState: any, version: number) => {
        // If version is old or doesn't exist, update to new profiles
        if (!version || version < 2) {
          // Get custom profiles (non-default ones created by user)
          const customProfiles = persistedState?.profiles?.filter((p: VehicleProfile) => !p.isDefault) || [];
          
          return {
            ...persistedState,
            version: 2,
            profiles: [...DEFAULT_PROFILES, ...customProfiles],
            settings: {
              ...persistedState?.settings,
              // If active profile no longer exists, switch to default
              activeProfileId: DEFAULT_PROFILES.find(p => p.id === persistedState?.settings?.activeProfileId)
                ? persistedState.settings.activeProfileId
                : 'standard-flatbed-5axle',
            },
          };
        }
        
        return persistedState;
      },
    }
  )
);
