/**
 * RoadScope Read-Only Firestore Client (for the Claude AI Assistant)
 *
 * Direct Firestore reads scoped to the RoadScope collections that live alongside
 * MeasurePRO's own data in the shared `os-hub-db` Firebase project. The AI uses
 * this to surface obstacles, routes, and pre-computed Route Intelligence results
 * for the user's active or nearby surveys.
 *
 * READ-ONLY by design. The AI never writes to RoadScope through this module —
 * any AI-proposed mutations go through MeasurePRO's local POI flow first, and
 * the existing sync engine (src/lib/roadscope/syncService.ts) pushes them up to
 * RoadScope as part of the normal user-approved sync.
 *
 * Architectural notes:
 * - The Firestore client is the same one MeasurePRO already uses (db from
 *   src/lib/firebase.ts). Same project, same auth, same security rules.
 * - The 9 SolTec data sources (SolTecWorld / SolTecUSA / SolTecQC / SolTecCAN /
 *   SolTecON / SolTecQC 511 / SolTecDE / SolTecFR / SolTecNL) are all already
 *   integrated server-side by RoadScope's Route Intelligence pipeline. Their
 *   results land in `routeIntelligenceCache/`, and the imported POIs land in
 *   `surveys/{id}/pois/`. We just consume them.
 * - Brand naming rule: in any string this module surfaces to the user, ALWAYS
 *   use the SolTec labels — never OpenStreetMap, NBI, MTMD, etc.
 *
 * Schema reference (verified 2026-04-11):
 *   surveys/{id}                       — survey doc
 *   surveys/{id}/pois/                 — POIs created NATIVELY in RoadScope UI
 *                                        (full SolTec taxonomy)
 *   surveys/{id}/RoadScope-POIs/       — POIs synced FROM MeasurePRO into RS
 *                                        (MeasurePRO's collaborator data)
 *   routes/                            — TOP-LEVEL routes (NOT a subcollection)
 *   routeIntelligenceCache/{cacheKey}  — pre-computed RI analysis
 *                                        cacheKey = ri_{routeId16}_{djb2(...)}
 *   riSourceCache/{tileKey}            — server-cached NBI tiles (read seldom)
 */

import {
  collection,
  collectionGroup,
  doc,
  getDoc,
  getDocs,
  query,
  where,
  limit as fsLimit,
  Firestore,
} from 'firebase/firestore';
import { db, getCurrentUser } from '../firebase';
import { getSyncStatus } from '../roadscope/syncService';

// ── Types surfaced to the AI ─────────────────────────────────────────────────

/**
 * Origin of a POI returned by combined queries. The AI uses this to reason
 * about authority and freshness.
 */
export type PoiOrigin =
  /** Captured live in MeasurePRO, lives in IndexedDB. Most current. */
  | 'mp-local'
  /** POI created natively in RoadScope UI by a route surveyor. Authoritative for the SolTec taxonomy. */
  | 'roadscope-manual'
  /** POI synced INTO RoadScope from a MeasurePRO instance (you or a collaborator). */
  | 'roadscope-sync'
  /** POI auto-generated by Route Intelligence from one of the 9 SolTec sources. */
  | 'roadscope-ri';

export interface CombinedPoi {
  id: string;
  origin: PoiOrigin;
  /** RoadScope POI type string (e.g., "Bridge", "STUSA-Bridge", "STWo-PowerLine") */
  type: string;
  name?: string;
  description?: string;
  notes?: string;
  latitude: number;
  longitude: number;
  /** Vertical clearance in meters when known (NBI / MTMD / OSM maxheight). */
  verticalClearanceM?: number;
  /** Load rating in metric tons when known (NBI). */
  loadRatingMetricTons?: number;
  /** NBI condition rating 0-9 when known. */
  conditionRating?: number;
  /** Computed: bridge is critical (Poor || clearance<4m || rating<36t). */
  isCritical?: boolean;
  /** Manual or auto-assigned operational badges. */
  badges?: string[];
  /** RoadScope source label, already SolTec-branded ("SolTecUSA", "SolTecWorld", etc.). */
  sourceLabel?: string;
  /** Distance from query center in meters (set by getObstaclesNearby). */
  distanceM?: number;
  /** Survey id this POI belongs to (RoadScope side). */
  surveyId?: string;
  /** True if archived (not deleted). */
  archived?: boolean;
}

export interface RoadScopeRouteSummary {
  id: string;
  surveyId?: string;
  surveyName: string;
  surveyPhase?: 'pre-survey' | 'field' | 'customer';
  pathSampleStart?: { lat: number; lng: number };
  pathSampleEnd?: { lat: number; lng: number };
  pathLength: number;
  archived?: boolean;
}

export interface RouteIntelligenceItem {
  uid: string;
  /** Real upstream source. We translate to SolTec labels in formatSourceLabel(). */
  source: string;
  categoryId: string;
  categoryLabel: string;
  name: string;
  latitude: number;
  longitude: number;
  notes?: string;
  typeKey: string;
  badge?: string;
  detail?: string;
  verticalClearanceM?: number;
  loadRatingMetricTons?: number;
  isCritical?: boolean;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Map an internal upstream source name (NBI, OSM, MTMD, NRN, ON511, QC511,
 * BAST, FRDG, NDW) to the SolTec brand label that the AI must use in its
 * outputs. The internal names should NEVER reach a user-visible string —
 * always pass through this function first.
 */
export function formatSourceLabel(source: string | undefined | null): string {
  if (!source) return '';
  const map: Record<string, string> = {
    OSM: 'SolTecWorld',
    NBI: 'SolTecUSA',
    MTMD: 'SolTecQC',
    NRN: 'SolTecCAN',
    ON511: 'SolTecON',
    QC511: 'SolTecQC 511',
    BAST: 'SolTecDE',
    FRDG: 'SolTecFR',
    NDW: 'SolTecNL',
  };
  return map[source] || source;
}

/**
 * Critical bridge formula. Mirrors RoadScope's own definition:
 *   Poor condition || vertical clearance < 4.0 m || operating rating < 36 t
 */
export function isBridgeCritical(opts: {
  conditionRating?: number;
  verticalClearanceM?: number;
  loadRatingMetricTons?: number;
}): boolean {
  const { conditionRating, verticalClearanceM, loadRatingMetricTons } = opts;
  if (typeof conditionRating === 'number' && conditionRating <= 4) return true;
  if (typeof verticalClearanceM === 'number' && verticalClearanceM < 4.0) return true;
  if (typeof loadRatingMetricTons === 'number' && loadRatingMetricTons < 36) return true;
  return false;
}

/**
 * NBI condition rating to semantic bucket. Mirrors RoadScope's mapping.
 *   7-9 = Good, 5-6 = Fair, 0-4 = Poor.
 */
export function conditionFromRating(rating: number | undefined | null): 'Good' | 'Fair' | 'Poor' | 'Unknown' {
  if (typeof rating !== 'number') return 'Unknown';
  if (rating >= 7) return 'Good';
  if (rating >= 5) return 'Fair';
  return 'Poor';
}

/**
 * Haversine distance in meters between two coordinates.
 */
export function haversineMeters(lat1: number, lng1: number, lat2: number, lng2: number): number {
  const R = 6371000;
  const dLat = (lat2 - lat1) * Math.PI / 180;
  const dLng = (lng2 - lng1) * Math.PI / 180;
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) * Math.sin(dLng / 2) ** 2;
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

/**
 * Bearing from point A to point B in degrees (0 = north, 90 = east).
 */
export function bearingDeg(lat1: number, lng1: number, lat2: number, lng2: number): number {
  const φ1 = lat1 * Math.PI / 180;
  const φ2 = lat2 * Math.PI / 180;
  const Δλ = (lng2 - lng1) * Math.PI / 180;
  const y = Math.sin(Δλ) * Math.cos(φ2);
  const x = Math.cos(φ1) * Math.sin(φ2) - Math.sin(φ1) * Math.cos(φ2) * Math.cos(Δλ);
  const θ = Math.atan2(y, x);
  return ((θ * 180 / Math.PI) + 360) % 360;
}

/**
 * Returns true if `target` falls within the angular cone centered on
 * `headingDeg` with half-angle `halfAngleDeg`. Used for "what's ahead of me"
 * filtering when the user has a heading.
 */
export function isWithinHeadingCone(
  centerLat: number, centerLng: number,
  targetLat: number, targetLng: number,
  headingDeg: number,
  halfAngleDeg: number = 60,
): boolean {
  const target = bearingDeg(centerLat, centerLng, targetLat, targetLng);
  let diff = Math.abs(target - headingDeg);
  if (diff > 180) diff = 360 - diff;
  return diff <= halfAngleDeg;
}

/**
 * Bounding box (degrees) around a center point that covers ~radiusMeters in
 * every direction. Cheap pre-filter so Firestore queries don't pull the entire
 * collection. Real distance check happens client-side after.
 */
function bboxForRadius(lat: number, lng: number, radiusMeters: number) {
  const latDelta = radiusMeters / 111_320; // 1 deg lat ≈ 111.32 km
  const lngDelta = radiusMeters / (111_320 * Math.cos(lat * Math.PI / 180));
  return {
    minLat: lat - latDelta,
    maxLat: lat + latDelta,
    minLng: lng - lngDelta,
    maxLng: lng + lngDelta,
  };
}

function isLikelyArchived(d: any): boolean {
  return d?.archived === true;
}

function getDb(): Firestore | null {
  if (!db) return null;
  return db as Firestore;
}

// ── Survey discovery ─────────────────────────────────────────────────────────

/**
 * Resolve the RoadScope survey id linked to the given MeasurePRO survey.
 * Returns null if the MeasurePRO survey hasn't been synced to RoadScope yet.
 */
export async function getLinkedRoadScopeSurveyId(measureproSurveyId: string): Promise<string | null> {
  try {
    const status = await getSyncStatus(measureproSurveyId);
    return status?.roadscopeSurveyId || null;
  } catch (e) {
    console.warn('[roadscopeReader] getLinkedRoadScopeSurveyId failed:', e);
    return null;
  }
}

/**
 * List the RoadScope surveys the current user can read. Filtered server-side
 * by Firestore rules — we just request `surveys/` and let the rules limit it.
 * Defensive: also filter client-side by createdBy or collaborators if both
 * fields exist on the doc.
 */
export async function listVisibleRoadScopeSurveys(maxResults: number = 25): Promise<Array<{
  id: string;
  name: string;
  customerName?: string;
  surveyPhase?: string;
  overhaulHeight?: string;
  overhaulHeightUnit?: 'ft' | 'm';
  externalId?: string;
  archived?: boolean;
}>> {
  const fs = getDb();
  if (!fs) return [];
  try {
    const q = query(collection(fs, 'surveys'), fsLimit(maxResults));
    const snap = await getDocs(q);
    const out: any[] = [];
    snap.forEach(d => {
      const data: any = d.data();
      if (isLikelyArchived(data)) return;
      out.push({
        id: d.id,
        name: data.name || data.surveyTitle || '(untitled)',
        customerName: data.customerName || data.clientName,
        surveyPhase: data.surveyPhase,
        overhaulHeight: data.overhaulHeight,
        overhaulHeightUnit: data.overhaulHeightUnit,
        externalId: data.externalId,
        archived: data.archived,
      });
    });
    return out;
  } catch (e) {
    console.warn('[roadscopeReader] listVisibleRoadScopeSurveys failed:', e);
    return [];
  }
}

// ── POI queries ──────────────────────────────────────────────────────────────

/**
 * Read POIs from a single subcollection of a single RoadScope survey,
 * pre-filtered by bbox, post-filtered by exact distance.
 *
 * `subcollection` MUST be either 'pois' (RoadScope-native, route surveyors)
 * or 'RoadScope-POIs' (synced from MeasurePRO).
 */
async function readPoiSubcollectionWithinRadius(
  surveyId: string,
  subcollection: 'pois' | 'RoadScope-POIs',
  centerLat: number,
  centerLng: number,
  radiusMeters: number,
  maxResults: number,
): Promise<CombinedPoi[]> {
  const fs = getDb();
  if (!fs) return [];

  try {
    const path = `surveys/${surveyId}/${subcollection}`;
    // Firestore can't index nested coordinates.latitude with a range AND have
    // an unrelated equality. We pull a wider candidate set then filter.
    const colRef = collection(fs, path);
    // We can't easily compose two range filters in Firestore (single range/order),
    // so we pull up to maxResults*4 and let the post-filter trim.
    const q = query(colRef, fsLimit(Math.min(500, maxResults * 4)));
    const snap = await getDocs(q);

    const origin: PoiOrigin = subcollection === 'pois' ? 'roadscope-manual' : 'roadscope-sync';

    const out: CombinedPoi[] = [];
    snap.forEach(d => {
      const data: any = d.data();
      if (isLikelyArchived(data)) return;
      const lat = data?.coordinates?.latitude;
      const lng = data?.coordinates?.longitude;
      if (typeof lat !== 'number' || typeof lng !== 'number') return;

      const dist = haversineMeters(centerLat, centerLng, lat, lng);
      if (dist > radiusMeters) return;

      // Detect Route Intelligence auto-generated POIs by typeKey prefix and
      // re-classify their origin. The data still lives in pois/, but it
      // didn't come from a human surveyor — it came from one of the 9
      // SolTec sources via the RI pipeline.
      const type = data.type || '';
      let resolvedOrigin: PoiOrigin = origin;
      if (typeof type === 'string' && (type.startsWith('STUSA-') || type.startsWith('STWo-') || type.startsWith('STQC-'))) {
        resolvedOrigin = 'roadscope-ri';
      }

      out.push({
        id: d.id,
        origin: resolvedOrigin,
        type,
        name: data.name,
        description: data.description,
        notes: data.notes,
        latitude: lat,
        longitude: lng,
        verticalClearanceM: data.verticalClearanceM,
        loadRatingMetricTons: data.loadRatingMetricTons,
        conditionRating: data.conditionRating,
        isCritical: data.isCritical ?? isBridgeCritical({
          conditionRating: data.conditionRating,
          verticalClearanceM: data.verticalClearanceM,
          loadRatingMetricTons: data.loadRatingMetricTons,
        }),
        badges: Array.isArray(data.badges) ? data.badges : undefined,
        sourceLabel: formatSourceLabel(data.source),
        distanceM: dist,
        surveyId,
        archived: data.archived,
      });
    });

    out.sort((a, b) => (a.distanceM || 0) - (b.distanceM || 0));
    return out.slice(0, maxResults);
  } catch (e) {
    console.warn(`[roadscopeReader] readPoiSubcollection ${subcollection} failed for ${surveyId}:`, e);
    return [];
  }
}

/**
 * Get all POIs from RoadScope within `radiusMeters` of (lat, lng).
 *
 * If `surveyIds` is provided, only those surveys are queried. Otherwise the
 * function queries `listVisibleRoadScopeSurveys()` to discover what the user
 * can read, then fans out across each survey's two POI subcollections
 * (pois + RoadScope-POIs).
 *
 * Result includes POIs from BOTH subcollections, marked with distinct
 * `origin` values so the AI can reason about authority.
 */
export async function getRoadScopePoisNearby(opts: {
  latitude: number;
  longitude: number;
  radiusMeters: number;
  surveyIds?: string[];
  maxResultsPerSurvey?: number;
}): Promise<CombinedPoi[]> {
  const {
    latitude,
    longitude,
    radiusMeters,
    surveyIds: explicitSurveyIds,
    maxResultsPerSurvey = 100,
  } = opts;

  const fs = getDb();
  if (!fs) return [];

  let surveyIds: string[] = [];
  if (explicitSurveyIds && explicitSurveyIds.length > 0) {
    surveyIds = explicitSurveyIds;
  } else {
    const visible = await listVisibleRoadScopeSurveys(50);
    surveyIds = visible.map(s => s.id);
  }
  if (surveyIds.length === 0) return [];

  const allResults: CombinedPoi[] = [];
  // Sequential per-survey to keep Firestore client healthy on cellular networks
  for (const surveyId of surveyIds) {
    const fromManual = await readPoiSubcollectionWithinRadius(
      surveyId, 'pois', latitude, longitude, radiusMeters, maxResultsPerSurvey
    );
    const fromSync = await readPoiSubcollectionWithinRadius(
      surveyId, 'RoadScope-POIs', latitude, longitude, radiusMeters, maxResultsPerSurvey
    );
    allResults.push(...fromManual, ...fromSync);
  }

  // Dedupe by (latitude, longitude) bucket within 30m, mirroring RoadScope's
  // own MERGE step in the Route Intelligence pipeline. We keep the entry with
  // the most "authoritative" origin (manual > ri > sync > local).
  const ORIGIN_RANK: Record<PoiOrigin, number> = {
    'roadscope-manual': 4,
    'roadscope-ri': 3,
    'roadscope-sync': 2,
    'mp-local': 1,
  };
  const deduped: CombinedPoi[] = [];
  for (const poi of allResults) {
    const dup = deduped.find(d =>
      d.type === poi.type &&
      haversineMeters(d.latitude, d.longitude, poi.latitude, poi.longitude) < 30
    );
    if (dup) {
      if (ORIGIN_RANK[poi.origin] > ORIGIN_RANK[dup.origin]) {
        Object.assign(dup, poi);
      }
    } else {
      deduped.push(poi);
    }
  }
  deduped.sort((a, b) => (a.distanceM || 0) - (b.distanceM || 0));
  return deduped;
}

/**
 * Subset of getRoadScopePoisNearby focused on bridges flagged critical
 * (Poor || clearance < 4.0m || rating < 36t). Use this when the user is
 * planning a heavy haul and wants to surface the show-stoppers.
 */
export async function getCriticalBridgesNearby(opts: {
  latitude: number;
  longitude: number;
  radiusMeters: number;
  convoyHeightM?: number;
}): Promise<CombinedPoi[]> {
  const all = await getRoadScopePoisNearby({
    latitude: opts.latitude,
    longitude: opts.longitude,
    radiusMeters: opts.radiusMeters,
  });
  return all.filter(p => {
    // Treat anything that LOOKS like a bridge as a candidate.
    const isBridge =
      p.type === 'Bridge' ||
      p.type === 'STUSA-Bridge' ||
      p.type === 'STWo-Bridge' ||
      p.type === 'STQC-Bridge' ||
      p.type === 'STWo-CriticalBridge' ||
      p.type === 'Overpass';
    if (!isBridge) return false;
    if (p.isCritical) return true;
    if (typeof opts.convoyHeightM === 'number' && typeof p.verticalClearanceM === 'number') {
      // Less than 30 cm of margin counts as critical for the convoy.
      if (p.verticalClearanceM - opts.convoyHeightM < 0.3) return true;
    }
    return false;
  });
}

// ── Route queries ────────────────────────────────────────────────────────────

/**
 * Reads the top-level `routes/` collection (NOT a subcollection of surveys —
 * verified with JF 2026-04-11). Returns route summaries near a point. We
 * sample the path's start/end and use those for distance filtering.
 */
export async function getRoadScopeRoutesNearby(opts: {
  latitude: number;
  longitude: number;
  radiusMeters: number;
  surveyPhase?: 'pre-survey' | 'field' | 'customer';
  maxResults?: number;
}): Promise<RoadScopeRouteSummary[]> {
  const fs = getDb();
  if (!fs) return [];
  const max = opts.maxResults ?? 50;

  try {
    const colRef = collection(fs, 'routes');
    // Firestore filtering on nested arrays is limited; pull and post-filter.
    const q = opts.surveyPhase
      ? query(colRef, where('surveyPhase', '==', opts.surveyPhase), fsLimit(max * 4))
      : query(colRef, fsLimit(max * 4));
    const snap = await getDocs(q);

    const out: RoadScopeRouteSummary[] = [];
    snap.forEach(d => {
      const data: any = d.data();
      if (isLikelyArchived(data)) return;
      const path: any[] = Array.isArray(data.path) ? data.path : [];
      if (path.length === 0) return;

      // Use start, midpoint, and end as cheap probes
      const start = path[0];
      const end = path[path.length - 1];
      const mid = path[Math.floor(path.length / 2)];
      const probes = [start, mid, end].filter(p => typeof p?.lat === 'number' && typeof p?.lng === 'number');
      const minDist = probes.reduce(
        (m, p) => Math.min(m, haversineMeters(opts.latitude, opts.longitude, p.lat, p.lng)),
        Infinity
      );
      if (minDist > opts.radiusMeters) return;

      out.push({
        id: d.id,
        surveyId: data.surveyId,
        surveyName: data.surveyName || data.name || '(unnamed route)',
        surveyPhase: data.surveyPhase,
        pathSampleStart: start && typeof start.lat === 'number' ? { lat: start.lat, lng: start.lng } : undefined,
        pathSampleEnd: end && typeof end.lat === 'number' ? { lat: end.lat, lng: end.lng } : undefined,
        pathLength: path.length,
        archived: data.archived,
      });
    });
    return out.slice(0, max);
  } catch (e) {
    console.warn('[roadscopeReader] getRoadScopeRoutesNearby failed:', e);
    return [];
  }
}

// ── Route Intelligence cache reads ──────────────────────────────────────────

/**
 * Look up the most recent Route Intelligence cache entry for a route. The
 * cacheKey format is `ri_{routeId16chars}_{djb2hash}` and we don't know the
 * djb2 portion ahead of time — instead we query for any cacheKey starting with
 * the routeId prefix.
 *
 * Note: Firestore can't do prefix queries directly. We use the standard
 * trick of `>= prefix` AND `< prefix + '\uf8ff'` on the document id.
 */
export async function getRouteIntelligenceForRoute(routeId: string): Promise<RouteIntelligenceItem[]> {
  const fs = getDb();
  if (!fs) return [];

  // routeId is up to 16 chars in the cache key
  const idPrefix = `ri_${routeId.slice(0, 16)}_`;

  try {
    // Firestore documentId() prefix range query
    const cacheCol = collection(fs, 'routeIntelligenceCache');
    // We can't easily filter by document id prefix without an index, so as a
    // simple fallback we fetch a recent slice and filter client-side. For a
    // production deployment we'd add a `routeId` field on the cache docs.
    const q = query(cacheCol, fsLimit(200));
    const snap = await getDocs(q);

    let bestItems: any[] = [];
    let bestUpdatedAt = 0;
    snap.forEach(d => {
      if (!d.id.startsWith(idPrefix)) return;
      const data: any = d.data();
      const t = data?.cachedAt?.toMillis ? data.cachedAt.toMillis() : 0;
      if (t > bestUpdatedAt && Array.isArray(data.items)) {
        bestUpdatedAt = t;
        bestItems = data.items;
      }
    });

    return bestItems.map((item: any) => ({
      uid: item.uid || '',
      source: item.source || '',
      categoryId: item.categoryId || '',
      categoryLabel: item.categoryLabel || '',
      name: item.name || '',
      latitude: item.lat,
      longitude: item.lng,
      notes: item.notes,
      typeKey: item.typeKey || '',
      badge: item.badge,
      detail: item.detail,
      verticalClearanceM: item.nbiRaw?.verticalClearanceMeters,
      loadRatingMetricTons: item.nbiRaw?.loadRatingTons,
      isCritical: item.nbiRaw?.isCritical,
    }));
  } catch (e) {
    console.warn('[roadscopeReader] getRouteIntelligenceForRoute failed:', e);
    return [];
  }
}

// ── Convenience: combine + filter for "what's around me" ────────────────────

/**
 * High-level query the AI uses for "what's around me". Combines RoadScope POIs
 * (both subcollections) with a heading-cone filter when the user is moving,
 * and flags Danger by overhaulHeight if available.
 */
export async function getObstaclesAroundUser(opts: {
  latitude: number;
  longitude: number;
  radiusMeters: number;
  headingDeg?: number;
  headingHalfAngleDeg?: number;
  convoyHeightM?: number;
  surveyIds?: string[];
}): Promise<CombinedPoi[]> {
  const pois = await getRoadScopePoisNearby({
    latitude: opts.latitude,
    longitude: opts.longitude,
    radiusMeters: opts.radiusMeters,
    surveyIds: opts.surveyIds,
  });

  let filtered = pois;
  if (typeof opts.headingDeg === 'number') {
    const half = opts.headingHalfAngleDeg ?? 60;
    filtered = filtered.filter(p =>
      isWithinHeadingCone(opts.latitude, opts.longitude, p.latitude, p.longitude, opts.headingDeg!, half)
    );
  }

  // Auto-flag Danger badge for bridges/overpasses if convoy height exceeds clearance
  if (typeof opts.convoyHeightM === 'number') {
    for (const p of filtered) {
      if (typeof p.verticalClearanceM === 'number' && p.verticalClearanceM < opts.convoyHeightM) {
        p.badges = Array.from(new Set([...(p.badges || []), 'Danger']));
      }
    }
  }

  return filtered;
}

// Re-export user helper for the AI tools
export { getCurrentUser };
